// Code generated by ent, DO NOT EDIT.

package ruleexecution

import (
	"regulation/internal/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.RuleExecution {
	return predicate.RuleExecution(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.RuleExecution {
	return predicate.RuleExecution(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.RuleExecution {
	return predicate.RuleExecution(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.RuleExecution {
	return predicate.RuleExecution(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.RuleExecution {
	return predicate.RuleExecution(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.RuleExecution {
	return predicate.RuleExecution(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.RuleExecution {
	return predicate.RuleExecution(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.RuleExecution {
	return predicate.RuleExecution(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.RuleExecution {
	return predicate.RuleExecution(sql.FieldLTE(FieldID, id))
}

// RuleID applies equality check predicate on the "rule_id" field. It's identical to RuleIDEQ.
func RuleID(v uuid.UUID) predicate.RuleExecution {
	return predicate.RuleExecution(sql.FieldEQ(FieldRuleID, v))
}

// TransactionID applies equality check predicate on the "transaction_id" field. It's identical to TransactionIDEQ.
func TransactionID(v uuid.UUID) predicate.RuleExecution {
	return predicate.RuleExecution(sql.FieldEQ(FieldTransactionID, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v uuid.UUID) predicate.RuleExecution {
	return predicate.RuleExecution(sql.FieldEQ(FieldUserID, v))
}

// AmountCents applies equality check predicate on the "amount_cents" field. It's identical to AmountCentsEQ.
func AmountCents(v int64) predicate.RuleExecution {
	return predicate.RuleExecution(sql.FieldEQ(FieldAmountCents, v))
}

// SourceAccountID applies equality check predicate on the "source_account_id" field. It's identical to SourceAccountIDEQ.
func SourceAccountID(v uuid.UUID) predicate.RuleExecution {
	return predicate.RuleExecution(sql.FieldEQ(FieldSourceAccountID, v))
}

// TargetAccountID applies equality check predicate on the "target_account_id" field. It's identical to TargetAccountIDEQ.
func TargetAccountID(v uuid.UUID) predicate.RuleExecution {
	return predicate.RuleExecution(sql.FieldEQ(FieldTargetAccountID, v))
}

// ErrorMessage applies equality check predicate on the "error_message" field. It's identical to ErrorMessageEQ.
func ErrorMessage(v string) predicate.RuleExecution {
	return predicate.RuleExecution(sql.FieldEQ(FieldErrorMessage, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.RuleExecution {
	return predicate.RuleExecution(sql.FieldEQ(FieldCreatedAt, v))
}

// CompletedAt applies equality check predicate on the "completed_at" field. It's identical to CompletedAtEQ.
func CompletedAt(v time.Time) predicate.RuleExecution {
	return predicate.RuleExecution(sql.FieldEQ(FieldCompletedAt, v))
}

// RuleIDEQ applies the EQ predicate on the "rule_id" field.
func RuleIDEQ(v uuid.UUID) predicate.RuleExecution {
	return predicate.RuleExecution(sql.FieldEQ(FieldRuleID, v))
}

// RuleIDNEQ applies the NEQ predicate on the "rule_id" field.
func RuleIDNEQ(v uuid.UUID) predicate.RuleExecution {
	return predicate.RuleExecution(sql.FieldNEQ(FieldRuleID, v))
}

// RuleIDIn applies the In predicate on the "rule_id" field.
func RuleIDIn(vs ...uuid.UUID) predicate.RuleExecution {
	return predicate.RuleExecution(sql.FieldIn(FieldRuleID, vs...))
}

// RuleIDNotIn applies the NotIn predicate on the "rule_id" field.
func RuleIDNotIn(vs ...uuid.UUID) predicate.RuleExecution {
	return predicate.RuleExecution(sql.FieldNotIn(FieldRuleID, vs...))
}

// TransactionIDEQ applies the EQ predicate on the "transaction_id" field.
func TransactionIDEQ(v uuid.UUID) predicate.RuleExecution {
	return predicate.RuleExecution(sql.FieldEQ(FieldTransactionID, v))
}

// TransactionIDNEQ applies the NEQ predicate on the "transaction_id" field.
func TransactionIDNEQ(v uuid.UUID) predicate.RuleExecution {
	return predicate.RuleExecution(sql.FieldNEQ(FieldTransactionID, v))
}

// TransactionIDIn applies the In predicate on the "transaction_id" field.
func TransactionIDIn(vs ...uuid.UUID) predicate.RuleExecution {
	return predicate.RuleExecution(sql.FieldIn(FieldTransactionID, vs...))
}

// TransactionIDNotIn applies the NotIn predicate on the "transaction_id" field.
func TransactionIDNotIn(vs ...uuid.UUID) predicate.RuleExecution {
	return predicate.RuleExecution(sql.FieldNotIn(FieldTransactionID, vs...))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v uuid.UUID) predicate.RuleExecution {
	return predicate.RuleExecution(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v uuid.UUID) predicate.RuleExecution {
	return predicate.RuleExecution(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...uuid.UUID) predicate.RuleExecution {
	return predicate.RuleExecution(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...uuid.UUID) predicate.RuleExecution {
	return predicate.RuleExecution(sql.FieldNotIn(FieldUserID, vs...))
}

// AmountCentsEQ applies the EQ predicate on the "amount_cents" field.
func AmountCentsEQ(v int64) predicate.RuleExecution {
	return predicate.RuleExecution(sql.FieldEQ(FieldAmountCents, v))
}

// AmountCentsNEQ applies the NEQ predicate on the "amount_cents" field.
func AmountCentsNEQ(v int64) predicate.RuleExecution {
	return predicate.RuleExecution(sql.FieldNEQ(FieldAmountCents, v))
}

// AmountCentsIn applies the In predicate on the "amount_cents" field.
func AmountCentsIn(vs ...int64) predicate.RuleExecution {
	return predicate.RuleExecution(sql.FieldIn(FieldAmountCents, vs...))
}

// AmountCentsNotIn applies the NotIn predicate on the "amount_cents" field.
func AmountCentsNotIn(vs ...int64) predicate.RuleExecution {
	return predicate.RuleExecution(sql.FieldNotIn(FieldAmountCents, vs...))
}

// AmountCentsGT applies the GT predicate on the "amount_cents" field.
func AmountCentsGT(v int64) predicate.RuleExecution {
	return predicate.RuleExecution(sql.FieldGT(FieldAmountCents, v))
}

// AmountCentsGTE applies the GTE predicate on the "amount_cents" field.
func AmountCentsGTE(v int64) predicate.RuleExecution {
	return predicate.RuleExecution(sql.FieldGTE(FieldAmountCents, v))
}

// AmountCentsLT applies the LT predicate on the "amount_cents" field.
func AmountCentsLT(v int64) predicate.RuleExecution {
	return predicate.RuleExecution(sql.FieldLT(FieldAmountCents, v))
}

// AmountCentsLTE applies the LTE predicate on the "amount_cents" field.
func AmountCentsLTE(v int64) predicate.RuleExecution {
	return predicate.RuleExecution(sql.FieldLTE(FieldAmountCents, v))
}

// SourceAccountIDEQ applies the EQ predicate on the "source_account_id" field.
func SourceAccountIDEQ(v uuid.UUID) predicate.RuleExecution {
	return predicate.RuleExecution(sql.FieldEQ(FieldSourceAccountID, v))
}

// SourceAccountIDNEQ applies the NEQ predicate on the "source_account_id" field.
func SourceAccountIDNEQ(v uuid.UUID) predicate.RuleExecution {
	return predicate.RuleExecution(sql.FieldNEQ(FieldSourceAccountID, v))
}

// SourceAccountIDIn applies the In predicate on the "source_account_id" field.
func SourceAccountIDIn(vs ...uuid.UUID) predicate.RuleExecution {
	return predicate.RuleExecution(sql.FieldIn(FieldSourceAccountID, vs...))
}

// SourceAccountIDNotIn applies the NotIn predicate on the "source_account_id" field.
func SourceAccountIDNotIn(vs ...uuid.UUID) predicate.RuleExecution {
	return predicate.RuleExecution(sql.FieldNotIn(FieldSourceAccountID, vs...))
}

// SourceAccountIDGT applies the GT predicate on the "source_account_id" field.
func SourceAccountIDGT(v uuid.UUID) predicate.RuleExecution {
	return predicate.RuleExecution(sql.FieldGT(FieldSourceAccountID, v))
}

// SourceAccountIDGTE applies the GTE predicate on the "source_account_id" field.
func SourceAccountIDGTE(v uuid.UUID) predicate.RuleExecution {
	return predicate.RuleExecution(sql.FieldGTE(FieldSourceAccountID, v))
}

// SourceAccountIDLT applies the LT predicate on the "source_account_id" field.
func SourceAccountIDLT(v uuid.UUID) predicate.RuleExecution {
	return predicate.RuleExecution(sql.FieldLT(FieldSourceAccountID, v))
}

// SourceAccountIDLTE applies the LTE predicate on the "source_account_id" field.
func SourceAccountIDLTE(v uuid.UUID) predicate.RuleExecution {
	return predicate.RuleExecution(sql.FieldLTE(FieldSourceAccountID, v))
}

// TargetAccountIDEQ applies the EQ predicate on the "target_account_id" field.
func TargetAccountIDEQ(v uuid.UUID) predicate.RuleExecution {
	return predicate.RuleExecution(sql.FieldEQ(FieldTargetAccountID, v))
}

// TargetAccountIDNEQ applies the NEQ predicate on the "target_account_id" field.
func TargetAccountIDNEQ(v uuid.UUID) predicate.RuleExecution {
	return predicate.RuleExecution(sql.FieldNEQ(FieldTargetAccountID, v))
}

// TargetAccountIDIn applies the In predicate on the "target_account_id" field.
func TargetAccountIDIn(vs ...uuid.UUID) predicate.RuleExecution {
	return predicate.RuleExecution(sql.FieldIn(FieldTargetAccountID, vs...))
}

// TargetAccountIDNotIn applies the NotIn predicate on the "target_account_id" field.
func TargetAccountIDNotIn(vs ...uuid.UUID) predicate.RuleExecution {
	return predicate.RuleExecution(sql.FieldNotIn(FieldTargetAccountID, vs...))
}

// TargetAccountIDGT applies the GT predicate on the "target_account_id" field.
func TargetAccountIDGT(v uuid.UUID) predicate.RuleExecution {
	return predicate.RuleExecution(sql.FieldGT(FieldTargetAccountID, v))
}

// TargetAccountIDGTE applies the GTE predicate on the "target_account_id" field.
func TargetAccountIDGTE(v uuid.UUID) predicate.RuleExecution {
	return predicate.RuleExecution(sql.FieldGTE(FieldTargetAccountID, v))
}

// TargetAccountIDLT applies the LT predicate on the "target_account_id" field.
func TargetAccountIDLT(v uuid.UUID) predicate.RuleExecution {
	return predicate.RuleExecution(sql.FieldLT(FieldTargetAccountID, v))
}

// TargetAccountIDLTE applies the LTE predicate on the "target_account_id" field.
func TargetAccountIDLTE(v uuid.UUID) predicate.RuleExecution {
	return predicate.RuleExecution(sql.FieldLTE(FieldTargetAccountID, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.RuleExecution {
	return predicate.RuleExecution(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.RuleExecution {
	return predicate.RuleExecution(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.RuleExecution {
	return predicate.RuleExecution(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.RuleExecution {
	return predicate.RuleExecution(sql.FieldNotIn(FieldStatus, vs...))
}

// ErrorMessageEQ applies the EQ predicate on the "error_message" field.
func ErrorMessageEQ(v string) predicate.RuleExecution {
	return predicate.RuleExecution(sql.FieldEQ(FieldErrorMessage, v))
}

// ErrorMessageNEQ applies the NEQ predicate on the "error_message" field.
func ErrorMessageNEQ(v string) predicate.RuleExecution {
	return predicate.RuleExecution(sql.FieldNEQ(FieldErrorMessage, v))
}

// ErrorMessageIn applies the In predicate on the "error_message" field.
func ErrorMessageIn(vs ...string) predicate.RuleExecution {
	return predicate.RuleExecution(sql.FieldIn(FieldErrorMessage, vs...))
}

// ErrorMessageNotIn applies the NotIn predicate on the "error_message" field.
func ErrorMessageNotIn(vs ...string) predicate.RuleExecution {
	return predicate.RuleExecution(sql.FieldNotIn(FieldErrorMessage, vs...))
}

// ErrorMessageGT applies the GT predicate on the "error_message" field.
func ErrorMessageGT(v string) predicate.RuleExecution {
	return predicate.RuleExecution(sql.FieldGT(FieldErrorMessage, v))
}

// ErrorMessageGTE applies the GTE predicate on the "error_message" field.
func ErrorMessageGTE(v string) predicate.RuleExecution {
	return predicate.RuleExecution(sql.FieldGTE(FieldErrorMessage, v))
}

// ErrorMessageLT applies the LT predicate on the "error_message" field.
func ErrorMessageLT(v string) predicate.RuleExecution {
	return predicate.RuleExecution(sql.FieldLT(FieldErrorMessage, v))
}

// ErrorMessageLTE applies the LTE predicate on the "error_message" field.
func ErrorMessageLTE(v string) predicate.RuleExecution {
	return predicate.RuleExecution(sql.FieldLTE(FieldErrorMessage, v))
}

// ErrorMessageContains applies the Contains predicate on the "error_message" field.
func ErrorMessageContains(v string) predicate.RuleExecution {
	return predicate.RuleExecution(sql.FieldContains(FieldErrorMessage, v))
}

// ErrorMessageHasPrefix applies the HasPrefix predicate on the "error_message" field.
func ErrorMessageHasPrefix(v string) predicate.RuleExecution {
	return predicate.RuleExecution(sql.FieldHasPrefix(FieldErrorMessage, v))
}

// ErrorMessageHasSuffix applies the HasSuffix predicate on the "error_message" field.
func ErrorMessageHasSuffix(v string) predicate.RuleExecution {
	return predicate.RuleExecution(sql.FieldHasSuffix(FieldErrorMessage, v))
}

// ErrorMessageIsNil applies the IsNil predicate on the "error_message" field.
func ErrorMessageIsNil() predicate.RuleExecution {
	return predicate.RuleExecution(sql.FieldIsNull(FieldErrorMessage))
}

// ErrorMessageNotNil applies the NotNil predicate on the "error_message" field.
func ErrorMessageNotNil() predicate.RuleExecution {
	return predicate.RuleExecution(sql.FieldNotNull(FieldErrorMessage))
}

// ErrorMessageEqualFold applies the EqualFold predicate on the "error_message" field.
func ErrorMessageEqualFold(v string) predicate.RuleExecution {
	return predicate.RuleExecution(sql.FieldEqualFold(FieldErrorMessage, v))
}

// ErrorMessageContainsFold applies the ContainsFold predicate on the "error_message" field.
func ErrorMessageContainsFold(v string) predicate.RuleExecution {
	return predicate.RuleExecution(sql.FieldContainsFold(FieldErrorMessage, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.RuleExecution {
	return predicate.RuleExecution(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.RuleExecution {
	return predicate.RuleExecution(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.RuleExecution {
	return predicate.RuleExecution(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.RuleExecution {
	return predicate.RuleExecution(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.RuleExecution {
	return predicate.RuleExecution(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.RuleExecution {
	return predicate.RuleExecution(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.RuleExecution {
	return predicate.RuleExecution(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.RuleExecution {
	return predicate.RuleExecution(sql.FieldLTE(FieldCreatedAt, v))
}

// CompletedAtEQ applies the EQ predicate on the "completed_at" field.
func CompletedAtEQ(v time.Time) predicate.RuleExecution {
	return predicate.RuleExecution(sql.FieldEQ(FieldCompletedAt, v))
}

// CompletedAtNEQ applies the NEQ predicate on the "completed_at" field.
func CompletedAtNEQ(v time.Time) predicate.RuleExecution {
	return predicate.RuleExecution(sql.FieldNEQ(FieldCompletedAt, v))
}

// CompletedAtIn applies the In predicate on the "completed_at" field.
func CompletedAtIn(vs ...time.Time) predicate.RuleExecution {
	return predicate.RuleExecution(sql.FieldIn(FieldCompletedAt, vs...))
}

// CompletedAtNotIn applies the NotIn predicate on the "completed_at" field.
func CompletedAtNotIn(vs ...time.Time) predicate.RuleExecution {
	return predicate.RuleExecution(sql.FieldNotIn(FieldCompletedAt, vs...))
}

// CompletedAtGT applies the GT predicate on the "completed_at" field.
func CompletedAtGT(v time.Time) predicate.RuleExecution {
	return predicate.RuleExecution(sql.FieldGT(FieldCompletedAt, v))
}

// CompletedAtGTE applies the GTE predicate on the "completed_at" field.
func CompletedAtGTE(v time.Time) predicate.RuleExecution {
	return predicate.RuleExecution(sql.FieldGTE(FieldCompletedAt, v))
}

// CompletedAtLT applies the LT predicate on the "completed_at" field.
func CompletedAtLT(v time.Time) predicate.RuleExecution {
	return predicate.RuleExecution(sql.FieldLT(FieldCompletedAt, v))
}

// CompletedAtLTE applies the LTE predicate on the "completed_at" field.
func CompletedAtLTE(v time.Time) predicate.RuleExecution {
	return predicate.RuleExecution(sql.FieldLTE(FieldCompletedAt, v))
}

// CompletedAtIsNil applies the IsNil predicate on the "completed_at" field.
func CompletedAtIsNil() predicate.RuleExecution {
	return predicate.RuleExecution(sql.FieldIsNull(FieldCompletedAt))
}

// CompletedAtNotNil applies the NotNil predicate on the "completed_at" field.
func CompletedAtNotNil() predicate.RuleExecution {
	return predicate.RuleExecution(sql.FieldNotNull(FieldCompletedAt))
}

// HasRule applies the HasEdge predicate on the "rule" edge.
func HasRule() predicate.RuleExecution {
	return predicate.RuleExecution(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, RuleTable, RuleColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRuleWith applies the HasEdge predicate on the "rule" edge with a given conditions (other predicates).
func HasRuleWith(preds ...predicate.Rule) predicate.RuleExecution {
	return predicate.RuleExecution(func(s *sql.Selector) {
		step := newRuleStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasTransaction applies the HasEdge predicate on the "transaction" edge.
func HasTransaction() predicate.RuleExecution {
	return predicate.RuleExecution(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, TransactionTable, TransactionColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTransactionWith applies the HasEdge predicate on the "transaction" edge with a given conditions (other predicates).
func HasTransactionWith(preds ...predicate.Transaction) predicate.RuleExecution {
	return predicate.RuleExecution(func(s *sql.Selector) {
		step := newTransactionStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.RuleExecution {
	return predicate.RuleExecution(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.RuleExecution {
	return predicate.RuleExecution(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasTransfer applies the HasEdge predicate on the "transfer" edge.
func HasTransfer() predicate.RuleExecution {
	return predicate.RuleExecution(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, TransferTable, TransferColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTransferWith applies the HasEdge predicate on the "transfer" edge with a given conditions (other predicates).
func HasTransferWith(preds ...predicate.SavingsTransfer) predicate.RuleExecution {
	return predicate.RuleExecution(func(s *sql.Selector) {
		step := newTransferStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.RuleExecution) predicate.RuleExecution {
	return predicate.RuleExecution(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.RuleExecution) predicate.RuleExecution {
	return predicate.RuleExecution(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.RuleExecution) predicate.RuleExecution {
	return predicate.RuleExecution(sql.NotPredicates(p))
}
