// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"regulation/internal/ent/account"
	"regulation/internal/ent/item"
	"regulation/internal/ent/transaction"
	"regulation/internal/ent/user"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// AccountCreate is the builder for creating a Account entity.
type AccountCreate struct {
	config
	mutation *AccountMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetItemID sets the "item_id" field.
func (_c *AccountCreate) SetItemID(v uuid.UUID) *AccountCreate {
	_c.mutation.SetItemID(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *AccountCreate) SetUserID(v uuid.UUID) *AccountCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetPlaidID sets the "plaid_id" field.
func (_c *AccountCreate) SetPlaidID(v string) *AccountCreate {
	_c.mutation.SetPlaidID(v)
	return _c
}

// SetName sets the "name" field.
func (_c *AccountCreate) SetName(v string) *AccountCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetType sets the "type" field.
func (_c *AccountCreate) SetType(v account.Type) *AccountCreate {
	_c.mutation.SetType(v)
	return _c
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_c *AccountCreate) SetNillableType(v *account.Type) *AccountCreate {
	if v != nil {
		_c.SetType(*v)
	}
	return _c
}

// SetSubtype sets the "subtype" field.
func (_c *AccountCreate) SetSubtype(v string) *AccountCreate {
	_c.mutation.SetSubtype(v)
	return _c
}

// SetNillableSubtype sets the "subtype" field if the given value is not nil.
func (_c *AccountCreate) SetNillableSubtype(v *string) *AccountCreate {
	if v != nil {
		_c.SetSubtype(*v)
	}
	return _c
}

// SetMask sets the "mask" field.
func (_c *AccountCreate) SetMask(v string) *AccountCreate {
	_c.mutation.SetMask(v)
	return _c
}

// SetNillableMask sets the "mask" field if the given value is not nil.
func (_c *AccountCreate) SetNillableMask(v *string) *AccountCreate {
	if v != nil {
		_c.SetMask(*v)
	}
	return _c
}

// SetCurrentBalance sets the "current_balance" field.
func (_c *AccountCreate) SetCurrentBalance(v int64) *AccountCreate {
	_c.mutation.SetCurrentBalance(v)
	return _c
}

// SetNillableCurrentBalance sets the "current_balance" field if the given value is not nil.
func (_c *AccountCreate) SetNillableCurrentBalance(v *int64) *AccountCreate {
	if v != nil {
		_c.SetCurrentBalance(*v)
	}
	return _c
}

// SetAvailableBalance sets the "available_balance" field.
func (_c *AccountCreate) SetAvailableBalance(v int64) *AccountCreate {
	_c.mutation.SetAvailableBalance(v)
	return _c
}

// SetNillableAvailableBalance sets the "available_balance" field if the given value is not nil.
func (_c *AccountCreate) SetNillableAvailableBalance(v *int64) *AccountCreate {
	if v != nil {
		_c.SetAvailableBalance(*v)
	}
	return _c
}

// SetIsActive sets the "is_active" field.
func (_c *AccountCreate) SetIsActive(v bool) *AccountCreate {
	_c.mutation.SetIsActive(v)
	return _c
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_c *AccountCreate) SetNillableIsActive(v *bool) *AccountCreate {
	if v != nil {
		_c.SetIsActive(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *AccountCreate) SetCreatedAt(v time.Time) *AccountCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AccountCreate) SetNillableCreatedAt(v *time.Time) *AccountCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *AccountCreate) SetUpdatedAt(v time.Time) *AccountCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *AccountCreate) SetNillableUpdatedAt(v *time.Time) *AccountCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *AccountCreate) SetID(v uuid.UUID) *AccountCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *AccountCreate) SetNillableID(v *uuid.UUID) *AccountCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetItem sets the "item" edge to the Item entity.
func (_c *AccountCreate) SetItem(v *Item) *AccountCreate {
	return _c.SetItemID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_c *AccountCreate) SetUser(v *User) *AccountCreate {
	return _c.SetUserID(v.ID)
}

// AddTransactionIDs adds the "transactions" edge to the Transaction entity by IDs.
func (_c *AccountCreate) AddTransactionIDs(ids ...uuid.UUID) *AccountCreate {
	_c.mutation.AddTransactionIDs(ids...)
	return _c
}

// AddTransactions adds the "transactions" edges to the Transaction entity.
func (_c *AccountCreate) AddTransactions(v ...*Transaction) *AccountCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddTransactionIDs(ids...)
}

// Mutation returns the AccountMutation object of the builder.
func (_c *AccountCreate) Mutation() *AccountMutation {
	return _c.mutation
}

// Save creates the Account in the database.
func (_c *AccountCreate) Save(ctx context.Context) (*Account, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AccountCreate) SaveX(ctx context.Context) *Account {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AccountCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AccountCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AccountCreate) defaults() {
	if _, ok := _c.mutation.GetType(); !ok {
		v := account.DefaultType
		_c.mutation.SetType(v)
	}
	if _, ok := _c.mutation.CurrentBalance(); !ok {
		v := account.DefaultCurrentBalance
		_c.mutation.SetCurrentBalance(v)
	}
	if _, ok := _c.mutation.IsActive(); !ok {
		v := account.DefaultIsActive
		_c.mutation.SetIsActive(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := account.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := account.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := account.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AccountCreate) check() error {
	if _, ok := _c.mutation.ItemID(); !ok {
		return &ValidationError{Name: "item_id", err: errors.New(`ent: missing required field "Account.item_id"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "Account.user_id"`)}
	}
	if _, ok := _c.mutation.PlaidID(); !ok {
		return &ValidationError{Name: "plaid_id", err: errors.New(`ent: missing required field "Account.plaid_id"`)}
	}
	if v, ok := _c.mutation.PlaidID(); ok {
		if err := account.PlaidIDValidator(v); err != nil {
			return &ValidationError{Name: "plaid_id", err: fmt.Errorf(`ent: validator failed for field "Account.plaid_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Account.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := account.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Account.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "Account.type"`)}
	}
	if v, ok := _c.mutation.GetType(); ok {
		if err := account.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Account.type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CurrentBalance(); !ok {
		return &ValidationError{Name: "current_balance", err: errors.New(`ent: missing required field "Account.current_balance"`)}
	}
	if _, ok := _c.mutation.IsActive(); !ok {
		return &ValidationError{Name: "is_active", err: errors.New(`ent: missing required field "Account.is_active"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Account.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Account.updated_at"`)}
	}
	if len(_c.mutation.ItemIDs()) == 0 {
		return &ValidationError{Name: "item", err: errors.New(`ent: missing required edge "Account.item"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "Account.user"`)}
	}
	return nil
}

func (_c *AccountCreate) sqlSave(ctx context.Context) (*Account, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AccountCreate) createSpec() (*Account, *sqlgraph.CreateSpec) {
	var (
		_node = &Account{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(account.Table, sqlgraph.NewFieldSpec(account.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.PlaidID(); ok {
		_spec.SetField(account.FieldPlaidID, field.TypeString, value)
		_node.PlaidID = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(account.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.GetType(); ok {
		_spec.SetField(account.FieldType, field.TypeEnum, value)
		_node.Type = value
	}
	if value, ok := _c.mutation.Subtype(); ok {
		_spec.SetField(account.FieldSubtype, field.TypeString, value)
		_node.Subtype = value
	}
	if value, ok := _c.mutation.Mask(); ok {
		_spec.SetField(account.FieldMask, field.TypeString, value)
		_node.Mask = value
	}
	if value, ok := _c.mutation.CurrentBalance(); ok {
		_spec.SetField(account.FieldCurrentBalance, field.TypeInt64, value)
		_node.CurrentBalance = value
	}
	if value, ok := _c.mutation.AvailableBalance(); ok {
		_spec.SetField(account.FieldAvailableBalance, field.TypeInt64, value)
		_node.AvailableBalance = &value
	}
	if value, ok := _c.mutation.IsActive(); ok {
		_spec.SetField(account.FieldIsActive, field.TypeBool, value)
		_node.IsActive = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(account.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(account.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.ItemIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   account.ItemTable,
			Columns: []string{account.ItemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(item.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ItemID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   account.UserTable,
			Columns: []string{account.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.TransactionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   account.TransactionsTable,
			Columns: []string{account.TransactionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(transaction.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Account.Create().
//		SetItemID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AccountUpsert) {
//			SetItemID(v+v).
//		}).
//		Exec(ctx)
func (_c *AccountCreate) OnConflict(opts ...sql.ConflictOption) *AccountUpsertOne {
	_c.conflict = opts
	return &AccountUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Account.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AccountCreate) OnConflictColumns(columns ...string) *AccountUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AccountUpsertOne{
		create: _c,
	}
}

type (
	// AccountUpsertOne is the builder for "upsert"-ing
	//  one Account node.
	AccountUpsertOne struct {
		create *AccountCreate
	}

	// AccountUpsert is the "OnConflict" setter.
	AccountUpsert struct {
		*sql.UpdateSet
	}
)

// SetItemID sets the "item_id" field.
func (u *AccountUpsert) SetItemID(v uuid.UUID) *AccountUpsert {
	u.Set(account.FieldItemID, v)
	return u
}

// UpdateItemID sets the "item_id" field to the value that was provided on create.
func (u *AccountUpsert) UpdateItemID() *AccountUpsert {
	u.SetExcluded(account.FieldItemID)
	return u
}

// SetUserID sets the "user_id" field.
func (u *AccountUpsert) SetUserID(v uuid.UUID) *AccountUpsert {
	u.Set(account.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *AccountUpsert) UpdateUserID() *AccountUpsert {
	u.SetExcluded(account.FieldUserID)
	return u
}

// SetPlaidID sets the "plaid_id" field.
func (u *AccountUpsert) SetPlaidID(v string) *AccountUpsert {
	u.Set(account.FieldPlaidID, v)
	return u
}

// UpdatePlaidID sets the "plaid_id" field to the value that was provided on create.
func (u *AccountUpsert) UpdatePlaidID() *AccountUpsert {
	u.SetExcluded(account.FieldPlaidID)
	return u
}

// SetName sets the "name" field.
func (u *AccountUpsert) SetName(v string) *AccountUpsert {
	u.Set(account.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *AccountUpsert) UpdateName() *AccountUpsert {
	u.SetExcluded(account.FieldName)
	return u
}

// SetType sets the "type" field.
func (u *AccountUpsert) SetType(v account.Type) *AccountUpsert {
	u.Set(account.FieldType, v)
	return u
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *AccountUpsert) UpdateType() *AccountUpsert {
	u.SetExcluded(account.FieldType)
	return u
}

// SetSubtype sets the "subtype" field.
func (u *AccountUpsert) SetSubtype(v string) *AccountUpsert {
	u.Set(account.FieldSubtype, v)
	return u
}

// UpdateSubtype sets the "subtype" field to the value that was provided on create.
func (u *AccountUpsert) UpdateSubtype() *AccountUpsert {
	u.SetExcluded(account.FieldSubtype)
	return u
}

// ClearSubtype clears the value of the "subtype" field.
func (u *AccountUpsert) ClearSubtype() *AccountUpsert {
	u.SetNull(account.FieldSubtype)
	return u
}

// SetMask sets the "mask" field.
func (u *AccountUpsert) SetMask(v string) *AccountUpsert {
	u.Set(account.FieldMask, v)
	return u
}

// UpdateMask sets the "mask" field to the value that was provided on create.
func (u *AccountUpsert) UpdateMask() *AccountUpsert {
	u.SetExcluded(account.FieldMask)
	return u
}

// ClearMask clears the value of the "mask" field.
func (u *AccountUpsert) ClearMask() *AccountUpsert {
	u.SetNull(account.FieldMask)
	return u
}

// SetCurrentBalance sets the "current_balance" field.
func (u *AccountUpsert) SetCurrentBalance(v int64) *AccountUpsert {
	u.Set(account.FieldCurrentBalance, v)
	return u
}

// UpdateCurrentBalance sets the "current_balance" field to the value that was provided on create.
func (u *AccountUpsert) UpdateCurrentBalance() *AccountUpsert {
	u.SetExcluded(account.FieldCurrentBalance)
	return u
}

// AddCurrentBalance adds v to the "current_balance" field.
func (u *AccountUpsert) AddCurrentBalance(v int64) *AccountUpsert {
	u.Add(account.FieldCurrentBalance, v)
	return u
}

// SetAvailableBalance sets the "available_balance" field.
func (u *AccountUpsert) SetAvailableBalance(v int64) *AccountUpsert {
	u.Set(account.FieldAvailableBalance, v)
	return u
}

// UpdateAvailableBalance sets the "available_balance" field to the value that was provided on create.
func (u *AccountUpsert) UpdateAvailableBalance() *AccountUpsert {
	u.SetExcluded(account.FieldAvailableBalance)
	return u
}

// AddAvailableBalance adds v to the "available_balance" field.
func (u *AccountUpsert) AddAvailableBalance(v int64) *AccountUpsert {
	u.Add(account.FieldAvailableBalance, v)
	return u
}

// ClearAvailableBalance clears the value of the "available_balance" field.
func (u *AccountUpsert) ClearAvailableBalance() *AccountUpsert {
	u.SetNull(account.FieldAvailableBalance)
	return u
}

// SetIsActive sets the "is_active" field.
func (u *AccountUpsert) SetIsActive(v bool) *AccountUpsert {
	u.Set(account.FieldIsActive, v)
	return u
}

// UpdateIsActive sets the "is_active" field to the value that was provided on create.
func (u *AccountUpsert) UpdateIsActive() *AccountUpsert {
	u.SetExcluded(account.FieldIsActive)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AccountUpsert) SetUpdatedAt(v time.Time) *AccountUpsert {
	u.Set(account.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AccountUpsert) UpdateUpdatedAt() *AccountUpsert {
	u.SetExcluded(account.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Account.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(account.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *AccountUpsertOne) UpdateNewValues() *AccountUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(account.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(account.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Account.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *AccountUpsertOne) Ignore() *AccountUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AccountUpsertOne) DoNothing() *AccountUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AccountCreate.OnConflict
// documentation for more info.
func (u *AccountUpsertOne) Update(set func(*AccountUpsert)) *AccountUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AccountUpsert{UpdateSet: update})
	}))
	return u
}

// SetItemID sets the "item_id" field.
func (u *AccountUpsertOne) SetItemID(v uuid.UUID) *AccountUpsertOne {
	return u.Update(func(s *AccountUpsert) {
		s.SetItemID(v)
	})
}

// UpdateItemID sets the "item_id" field to the value that was provided on create.
func (u *AccountUpsertOne) UpdateItemID() *AccountUpsertOne {
	return u.Update(func(s *AccountUpsert) {
		s.UpdateItemID()
	})
}

// SetUserID sets the "user_id" field.
func (u *AccountUpsertOne) SetUserID(v uuid.UUID) *AccountUpsertOne {
	return u.Update(func(s *AccountUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *AccountUpsertOne) UpdateUserID() *AccountUpsertOne {
	return u.Update(func(s *AccountUpsert) {
		s.UpdateUserID()
	})
}

// SetPlaidID sets the "plaid_id" field.
func (u *AccountUpsertOne) SetPlaidID(v string) *AccountUpsertOne {
	return u.Update(func(s *AccountUpsert) {
		s.SetPlaidID(v)
	})
}

// UpdatePlaidID sets the "plaid_id" field to the value that was provided on create.
func (u *AccountUpsertOne) UpdatePlaidID() *AccountUpsertOne {
	return u.Update(func(s *AccountUpsert) {
		s.UpdatePlaidID()
	})
}

// SetName sets the "name" field.
func (u *AccountUpsertOne) SetName(v string) *AccountUpsertOne {
	return u.Update(func(s *AccountUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *AccountUpsertOne) UpdateName() *AccountUpsertOne {
	return u.Update(func(s *AccountUpsert) {
		s.UpdateName()
	})
}

// SetType sets the "type" field.
func (u *AccountUpsertOne) SetType(v account.Type) *AccountUpsertOne {
	return u.Update(func(s *AccountUpsert) {
		s.SetType(v)
	})
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *AccountUpsertOne) UpdateType() *AccountUpsertOne {
	return u.Update(func(s *AccountUpsert) {
		s.UpdateType()
	})
}

// SetSubtype sets the "subtype" field.
func (u *AccountUpsertOne) SetSubtype(v string) *AccountUpsertOne {
	return u.Update(func(s *AccountUpsert) {
		s.SetSubtype(v)
	})
}

// UpdateSubtype sets the "subtype" field to the value that was provided on create.
func (u *AccountUpsertOne) UpdateSubtype() *AccountUpsertOne {
	return u.Update(func(s *AccountUpsert) {
		s.UpdateSubtype()
	})
}

// ClearSubtype clears the value of the "subtype" field.
func (u *AccountUpsertOne) ClearSubtype() *AccountUpsertOne {
	return u.Update(func(s *AccountUpsert) {
		s.ClearSubtype()
	})
}

// SetMask sets the "mask" field.
func (u *AccountUpsertOne) SetMask(v string) *AccountUpsertOne {
	return u.Update(func(s *AccountUpsert) {
		s.SetMask(v)
	})
}

// UpdateMask sets the "mask" field to the value that was provided on create.
func (u *AccountUpsertOne) UpdateMask() *AccountUpsertOne {
	return u.Update(func(s *AccountUpsert) {
		s.UpdateMask()
	})
}

// ClearMask clears the value of the "mask" field.
func (u *AccountUpsertOne) ClearMask() *AccountUpsertOne {
	return u.Update(func(s *AccountUpsert) {
		s.ClearMask()
	})
}

// SetCurrentBalance sets the "current_balance" field.
func (u *AccountUpsertOne) SetCurrentBalance(v int64) *AccountUpsertOne {
	return u.Update(func(s *AccountUpsert) {
		s.SetCurrentBalance(v)
	})
}

// AddCurrentBalance adds v to the "current_balance" field.
func (u *AccountUpsertOne) AddCurrentBalance(v int64) *AccountUpsertOne {
	return u.Update(func(s *AccountUpsert) {
		s.AddCurrentBalance(v)
	})
}

// UpdateCurrentBalance sets the "current_balance" field to the value that was provided on create.
func (u *AccountUpsertOne) UpdateCurrentBalance() *AccountUpsertOne {
	return u.Update(func(s *AccountUpsert) {
		s.UpdateCurrentBalance()
	})
}

// SetAvailableBalance sets the "available_balance" field.
func (u *AccountUpsertOne) SetAvailableBalance(v int64) *AccountUpsertOne {
	return u.Update(func(s *AccountUpsert) {
		s.SetAvailableBalance(v)
	})
}

// AddAvailableBalance adds v to the "available_balance" field.
func (u *AccountUpsertOne) AddAvailableBalance(v int64) *AccountUpsertOne {
	return u.Update(func(s *AccountUpsert) {
		s.AddAvailableBalance(v)
	})
}

// UpdateAvailableBalance sets the "available_balance" field to the value that was provided on create.
func (u *AccountUpsertOne) UpdateAvailableBalance() *AccountUpsertOne {
	return u.Update(func(s *AccountUpsert) {
		s.UpdateAvailableBalance()
	})
}

// ClearAvailableBalance clears the value of the "available_balance" field.
func (u *AccountUpsertOne) ClearAvailableBalance() *AccountUpsertOne {
	return u.Update(func(s *AccountUpsert) {
		s.ClearAvailableBalance()
	})
}

// SetIsActive sets the "is_active" field.
func (u *AccountUpsertOne) SetIsActive(v bool) *AccountUpsertOne {
	return u.Update(func(s *AccountUpsert) {
		s.SetIsActive(v)
	})
}

// UpdateIsActive sets the "is_active" field to the value that was provided on create.
func (u *AccountUpsertOne) UpdateIsActive() *AccountUpsertOne {
	return u.Update(func(s *AccountUpsert) {
		s.UpdateIsActive()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AccountUpsertOne) SetUpdatedAt(v time.Time) *AccountUpsertOne {
	return u.Update(func(s *AccountUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AccountUpsertOne) UpdateUpdatedAt() *AccountUpsertOne {
	return u.Update(func(s *AccountUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *AccountUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AccountCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AccountUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *AccountUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: AccountUpsertOne.ID is not supported by MySQL driver. Use AccountUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *AccountUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// AccountCreateBulk is the builder for creating many Account entities in bulk.
type AccountCreateBulk struct {
	config
	err      error
	builders []*AccountCreate
	conflict []sql.ConflictOption
}

// Save creates the Account entities in the database.
func (_c *AccountCreateBulk) Save(ctx context.Context) ([]*Account, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Account, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AccountMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AccountCreateBulk) SaveX(ctx context.Context) []*Account {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AccountCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AccountCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Account.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AccountUpsert) {
//			SetItemID(v+v).
//		}).
//		Exec(ctx)
func (_c *AccountCreateBulk) OnConflict(opts ...sql.ConflictOption) *AccountUpsertBulk {
	_c.conflict = opts
	return &AccountUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Account.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AccountCreateBulk) OnConflictColumns(columns ...string) *AccountUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AccountUpsertBulk{
		create: _c,
	}
}

// AccountUpsertBulk is the builder for "upsert"-ing
// a bulk of Account nodes.
type AccountUpsertBulk struct {
	create *AccountCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Account.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(account.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *AccountUpsertBulk) UpdateNewValues() *AccountUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(account.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(account.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Account.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *AccountUpsertBulk) Ignore() *AccountUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AccountUpsertBulk) DoNothing() *AccountUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AccountCreateBulk.OnConflict
// documentation for more info.
func (u *AccountUpsertBulk) Update(set func(*AccountUpsert)) *AccountUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AccountUpsert{UpdateSet: update})
	}))
	return u
}

// SetItemID sets the "item_id" field.
func (u *AccountUpsertBulk) SetItemID(v uuid.UUID) *AccountUpsertBulk {
	return u.Update(func(s *AccountUpsert) {
		s.SetItemID(v)
	})
}

// UpdateItemID sets the "item_id" field to the value that was provided on create.
func (u *AccountUpsertBulk) UpdateItemID() *AccountUpsertBulk {
	return u.Update(func(s *AccountUpsert) {
		s.UpdateItemID()
	})
}

// SetUserID sets the "user_id" field.
func (u *AccountUpsertBulk) SetUserID(v uuid.UUID) *AccountUpsertBulk {
	return u.Update(func(s *AccountUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *AccountUpsertBulk) UpdateUserID() *AccountUpsertBulk {
	return u.Update(func(s *AccountUpsert) {
		s.UpdateUserID()
	})
}

// SetPlaidID sets the "plaid_id" field.
func (u *AccountUpsertBulk) SetPlaidID(v string) *AccountUpsertBulk {
	return u.Update(func(s *AccountUpsert) {
		s.SetPlaidID(v)
	})
}

// UpdatePlaidID sets the "plaid_id" field to the value that was provided on create.
func (u *AccountUpsertBulk) UpdatePlaidID() *AccountUpsertBulk {
	return u.Update(func(s *AccountUpsert) {
		s.UpdatePlaidID()
	})
}

// SetName sets the "name" field.
func (u *AccountUpsertBulk) SetName(v string) *AccountUpsertBulk {
	return u.Update(func(s *AccountUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *AccountUpsertBulk) UpdateName() *AccountUpsertBulk {
	return u.Update(func(s *AccountUpsert) {
		s.UpdateName()
	})
}

// SetType sets the "type" field.
func (u *AccountUpsertBulk) SetType(v account.Type) *AccountUpsertBulk {
	return u.Update(func(s *AccountUpsert) {
		s.SetType(v)
	})
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *AccountUpsertBulk) UpdateType() *AccountUpsertBulk {
	return u.Update(func(s *AccountUpsert) {
		s.UpdateType()
	})
}

// SetSubtype sets the "subtype" field.
func (u *AccountUpsertBulk) SetSubtype(v string) *AccountUpsertBulk {
	return u.Update(func(s *AccountUpsert) {
		s.SetSubtype(v)
	})
}

// UpdateSubtype sets the "subtype" field to the value that was provided on create.
func (u *AccountUpsertBulk) UpdateSubtype() *AccountUpsertBulk {
	return u.Update(func(s *AccountUpsert) {
		s.UpdateSubtype()
	})
}

// ClearSubtype clears the value of the "subtype" field.
func (u *AccountUpsertBulk) ClearSubtype() *AccountUpsertBulk {
	return u.Update(func(s *AccountUpsert) {
		s.ClearSubtype()
	})
}

// SetMask sets the "mask" field.
func (u *AccountUpsertBulk) SetMask(v string) *AccountUpsertBulk {
	return u.Update(func(s *AccountUpsert) {
		s.SetMask(v)
	})
}

// UpdateMask sets the "mask" field to the value that was provided on create.
func (u *AccountUpsertBulk) UpdateMask() *AccountUpsertBulk {
	return u.Update(func(s *AccountUpsert) {
		s.UpdateMask()
	})
}

// ClearMask clears the value of the "mask" field.
func (u *AccountUpsertBulk) ClearMask() *AccountUpsertBulk {
	return u.Update(func(s *AccountUpsert) {
		s.ClearMask()
	})
}

// SetCurrentBalance sets the "current_balance" field.
func (u *AccountUpsertBulk) SetCurrentBalance(v int64) *AccountUpsertBulk {
	return u.Update(func(s *AccountUpsert) {
		s.SetCurrentBalance(v)
	})
}

// AddCurrentBalance adds v to the "current_balance" field.
func (u *AccountUpsertBulk) AddCurrentBalance(v int64) *AccountUpsertBulk {
	return u.Update(func(s *AccountUpsert) {
		s.AddCurrentBalance(v)
	})
}

// UpdateCurrentBalance sets the "current_balance" field to the value that was provided on create.
func (u *AccountUpsertBulk) UpdateCurrentBalance() *AccountUpsertBulk {
	return u.Update(func(s *AccountUpsert) {
		s.UpdateCurrentBalance()
	})
}

// SetAvailableBalance sets the "available_balance" field.
func (u *AccountUpsertBulk) SetAvailableBalance(v int64) *AccountUpsertBulk {
	return u.Update(func(s *AccountUpsert) {
		s.SetAvailableBalance(v)
	})
}

// AddAvailableBalance adds v to the "available_balance" field.
func (u *AccountUpsertBulk) AddAvailableBalance(v int64) *AccountUpsertBulk {
	return u.Update(func(s *AccountUpsert) {
		s.AddAvailableBalance(v)
	})
}

// UpdateAvailableBalance sets the "available_balance" field to the value that was provided on create.
func (u *AccountUpsertBulk) UpdateAvailableBalance() *AccountUpsertBulk {
	return u.Update(func(s *AccountUpsert) {
		s.UpdateAvailableBalance()
	})
}

// ClearAvailableBalance clears the value of the "available_balance" field.
func (u *AccountUpsertBulk) ClearAvailableBalance() *AccountUpsertBulk {
	return u.Update(func(s *AccountUpsert) {
		s.ClearAvailableBalance()
	})
}

// SetIsActive sets the "is_active" field.
func (u *AccountUpsertBulk) SetIsActive(v bool) *AccountUpsertBulk {
	return u.Update(func(s *AccountUpsert) {
		s.SetIsActive(v)
	})
}

// UpdateIsActive sets the "is_active" field to the value that was provided on create.
func (u *AccountUpsertBulk) UpdateIsActive() *AccountUpsertBulk {
	return u.Update(func(s *AccountUpsert) {
		s.UpdateIsActive()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AccountUpsertBulk) SetUpdatedAt(v time.Time) *AccountUpsertBulk {
	return u.Update(func(s *AccountUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AccountUpsertBulk) UpdateUpdatedAt() *AccountUpsertBulk {
	return u.Update(func(s *AccountUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *AccountUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the AccountCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AccountCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AccountUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
