// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"regulation/internal/ent/pushsubscription"
	"regulation/internal/ent/user"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// PushSubscriptionCreate is the builder for creating a PushSubscription entity.
type PushSubscriptionCreate struct {
	config
	mutation *PushSubscriptionMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetUserID sets the "user_id" field.
func (_c *PushSubscriptionCreate) SetUserID(v uuid.UUID) *PushSubscriptionCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetEndpoint sets the "endpoint" field.
func (_c *PushSubscriptionCreate) SetEndpoint(v string) *PushSubscriptionCreate {
	_c.mutation.SetEndpoint(v)
	return _c
}

// SetP256dh sets the "p256dh" field.
func (_c *PushSubscriptionCreate) SetP256dh(v string) *PushSubscriptionCreate {
	_c.mutation.SetP256dh(v)
	return _c
}

// SetAuth sets the "auth" field.
func (_c *PushSubscriptionCreate) SetAuth(v string) *PushSubscriptionCreate {
	_c.mutation.SetAuth(v)
	return _c
}

// SetActive sets the "active" field.
func (_c *PushSubscriptionCreate) SetActive(v bool) *PushSubscriptionCreate {
	_c.mutation.SetActive(v)
	return _c
}

// SetNillableActive sets the "active" field if the given value is not nil.
func (_c *PushSubscriptionCreate) SetNillableActive(v *bool) *PushSubscriptionCreate {
	if v != nil {
		_c.SetActive(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *PushSubscriptionCreate) SetCreatedAt(v time.Time) *PushSubscriptionCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *PushSubscriptionCreate) SetNillableCreatedAt(v *time.Time) *PushSubscriptionCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *PushSubscriptionCreate) SetUpdatedAt(v time.Time) *PushSubscriptionCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *PushSubscriptionCreate) SetNillableUpdatedAt(v *time.Time) *PushSubscriptionCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *PushSubscriptionCreate) SetID(v uuid.UUID) *PushSubscriptionCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *PushSubscriptionCreate) SetNillableID(v *uuid.UUID) *PushSubscriptionCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *PushSubscriptionCreate) SetUser(v *User) *PushSubscriptionCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the PushSubscriptionMutation object of the builder.
func (_c *PushSubscriptionCreate) Mutation() *PushSubscriptionMutation {
	return _c.mutation
}

// Save creates the PushSubscription in the database.
func (_c *PushSubscriptionCreate) Save(ctx context.Context) (*PushSubscription, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PushSubscriptionCreate) SaveX(ctx context.Context) *PushSubscription {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PushSubscriptionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PushSubscriptionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PushSubscriptionCreate) defaults() {
	if _, ok := _c.mutation.Active(); !ok {
		v := pushsubscription.DefaultActive
		_c.mutation.SetActive(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := pushsubscription.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := pushsubscription.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := pushsubscription.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PushSubscriptionCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "PushSubscription.user_id"`)}
	}
	if _, ok := _c.mutation.Endpoint(); !ok {
		return &ValidationError{Name: "endpoint", err: errors.New(`ent: missing required field "PushSubscription.endpoint"`)}
	}
	if v, ok := _c.mutation.Endpoint(); ok {
		if err := pushsubscription.EndpointValidator(v); err != nil {
			return &ValidationError{Name: "endpoint", err: fmt.Errorf(`ent: validator failed for field "PushSubscription.endpoint": %w`, err)}
		}
	}
	if _, ok := _c.mutation.P256dh(); !ok {
		return &ValidationError{Name: "p256dh", err: errors.New(`ent: missing required field "PushSubscription.p256dh"`)}
	}
	if v, ok := _c.mutation.P256dh(); ok {
		if err := pushsubscription.P256dhValidator(v); err != nil {
			return &ValidationError{Name: "p256dh", err: fmt.Errorf(`ent: validator failed for field "PushSubscription.p256dh": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Auth(); !ok {
		return &ValidationError{Name: "auth", err: errors.New(`ent: missing required field "PushSubscription.auth"`)}
	}
	if v, ok := _c.mutation.Auth(); ok {
		if err := pushsubscription.AuthValidator(v); err != nil {
			return &ValidationError{Name: "auth", err: fmt.Errorf(`ent: validator failed for field "PushSubscription.auth": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Active(); !ok {
		return &ValidationError{Name: "active", err: errors.New(`ent: missing required field "PushSubscription.active"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "PushSubscription.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "PushSubscription.updated_at"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "PushSubscription.user"`)}
	}
	return nil
}

func (_c *PushSubscriptionCreate) sqlSave(ctx context.Context) (*PushSubscription, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PushSubscriptionCreate) createSpec() (*PushSubscription, *sqlgraph.CreateSpec) {
	var (
		_node = &PushSubscription{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(pushsubscription.Table, sqlgraph.NewFieldSpec(pushsubscription.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Endpoint(); ok {
		_spec.SetField(pushsubscription.FieldEndpoint, field.TypeString, value)
		_node.Endpoint = value
	}
	if value, ok := _c.mutation.P256dh(); ok {
		_spec.SetField(pushsubscription.FieldP256dh, field.TypeString, value)
		_node.P256dh = value
	}
	if value, ok := _c.mutation.Auth(); ok {
		_spec.SetField(pushsubscription.FieldAuth, field.TypeString, value)
		_node.Auth = value
	}
	if value, ok := _c.mutation.Active(); ok {
		_spec.SetField(pushsubscription.FieldActive, field.TypeBool, value)
		_node.Active = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(pushsubscription.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(pushsubscription.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pushsubscription.UserTable,
			Columns: []string{pushsubscription.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PushSubscription.Create().
//		SetUserID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PushSubscriptionUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *PushSubscriptionCreate) OnConflict(opts ...sql.ConflictOption) *PushSubscriptionUpsertOne {
	_c.conflict = opts
	return &PushSubscriptionUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PushSubscription.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PushSubscriptionCreate) OnConflictColumns(columns ...string) *PushSubscriptionUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PushSubscriptionUpsertOne{
		create: _c,
	}
}

type (
	// PushSubscriptionUpsertOne is the builder for "upsert"-ing
	//  one PushSubscription node.
	PushSubscriptionUpsertOne struct {
		create *PushSubscriptionCreate
	}

	// PushSubscriptionUpsert is the "OnConflict" setter.
	PushSubscriptionUpsert struct {
		*sql.UpdateSet
	}
)

// SetEndpoint sets the "endpoint" field.
func (u *PushSubscriptionUpsert) SetEndpoint(v string) *PushSubscriptionUpsert {
	u.Set(pushsubscription.FieldEndpoint, v)
	return u
}

// UpdateEndpoint sets the "endpoint" field to the value that was provided on create.
func (u *PushSubscriptionUpsert) UpdateEndpoint() *PushSubscriptionUpsert {
	u.SetExcluded(pushsubscription.FieldEndpoint)
	return u
}

// SetP256dh sets the "p256dh" field.
func (u *PushSubscriptionUpsert) SetP256dh(v string) *PushSubscriptionUpsert {
	u.Set(pushsubscription.FieldP256dh, v)
	return u
}

// UpdateP256dh sets the "p256dh" field to the value that was provided on create.
func (u *PushSubscriptionUpsert) UpdateP256dh() *PushSubscriptionUpsert {
	u.SetExcluded(pushsubscription.FieldP256dh)
	return u
}

// SetAuth sets the "auth" field.
func (u *PushSubscriptionUpsert) SetAuth(v string) *PushSubscriptionUpsert {
	u.Set(pushsubscription.FieldAuth, v)
	return u
}

// UpdateAuth sets the "auth" field to the value that was provided on create.
func (u *PushSubscriptionUpsert) UpdateAuth() *PushSubscriptionUpsert {
	u.SetExcluded(pushsubscription.FieldAuth)
	return u
}

// SetActive sets the "active" field.
func (u *PushSubscriptionUpsert) SetActive(v bool) *PushSubscriptionUpsert {
	u.Set(pushsubscription.FieldActive, v)
	return u
}

// UpdateActive sets the "active" field to the value that was provided on create.
func (u *PushSubscriptionUpsert) UpdateActive() *PushSubscriptionUpsert {
	u.SetExcluded(pushsubscription.FieldActive)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PushSubscriptionUpsert) SetUpdatedAt(v time.Time) *PushSubscriptionUpsert {
	u.Set(pushsubscription.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PushSubscriptionUpsert) UpdateUpdatedAt() *PushSubscriptionUpsert {
	u.SetExcluded(pushsubscription.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.PushSubscription.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(pushsubscription.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *PushSubscriptionUpsertOne) UpdateNewValues() *PushSubscriptionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(pushsubscription.FieldID)
		}
		if _, exists := u.create.mutation.UserID(); exists {
			s.SetIgnore(pushsubscription.FieldUserID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(pushsubscription.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PushSubscription.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *PushSubscriptionUpsertOne) Ignore() *PushSubscriptionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PushSubscriptionUpsertOne) DoNothing() *PushSubscriptionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PushSubscriptionCreate.OnConflict
// documentation for more info.
func (u *PushSubscriptionUpsertOne) Update(set func(*PushSubscriptionUpsert)) *PushSubscriptionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PushSubscriptionUpsert{UpdateSet: update})
	}))
	return u
}

// SetEndpoint sets the "endpoint" field.
func (u *PushSubscriptionUpsertOne) SetEndpoint(v string) *PushSubscriptionUpsertOne {
	return u.Update(func(s *PushSubscriptionUpsert) {
		s.SetEndpoint(v)
	})
}

// UpdateEndpoint sets the "endpoint" field to the value that was provided on create.
func (u *PushSubscriptionUpsertOne) UpdateEndpoint() *PushSubscriptionUpsertOne {
	return u.Update(func(s *PushSubscriptionUpsert) {
		s.UpdateEndpoint()
	})
}

// SetP256dh sets the "p256dh" field.
func (u *PushSubscriptionUpsertOne) SetP256dh(v string) *PushSubscriptionUpsertOne {
	return u.Update(func(s *PushSubscriptionUpsert) {
		s.SetP256dh(v)
	})
}

// UpdateP256dh sets the "p256dh" field to the value that was provided on create.
func (u *PushSubscriptionUpsertOne) UpdateP256dh() *PushSubscriptionUpsertOne {
	return u.Update(func(s *PushSubscriptionUpsert) {
		s.UpdateP256dh()
	})
}

// SetAuth sets the "auth" field.
func (u *PushSubscriptionUpsertOne) SetAuth(v string) *PushSubscriptionUpsertOne {
	return u.Update(func(s *PushSubscriptionUpsert) {
		s.SetAuth(v)
	})
}

// UpdateAuth sets the "auth" field to the value that was provided on create.
func (u *PushSubscriptionUpsertOne) UpdateAuth() *PushSubscriptionUpsertOne {
	return u.Update(func(s *PushSubscriptionUpsert) {
		s.UpdateAuth()
	})
}

// SetActive sets the "active" field.
func (u *PushSubscriptionUpsertOne) SetActive(v bool) *PushSubscriptionUpsertOne {
	return u.Update(func(s *PushSubscriptionUpsert) {
		s.SetActive(v)
	})
}

// UpdateActive sets the "active" field to the value that was provided on create.
func (u *PushSubscriptionUpsertOne) UpdateActive() *PushSubscriptionUpsertOne {
	return u.Update(func(s *PushSubscriptionUpsert) {
		s.UpdateActive()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PushSubscriptionUpsertOne) SetUpdatedAt(v time.Time) *PushSubscriptionUpsertOne {
	return u.Update(func(s *PushSubscriptionUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PushSubscriptionUpsertOne) UpdateUpdatedAt() *PushSubscriptionUpsertOne {
	return u.Update(func(s *PushSubscriptionUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *PushSubscriptionUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PushSubscriptionCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PushSubscriptionUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *PushSubscriptionUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: PushSubscriptionUpsertOne.ID is not supported by MySQL driver. Use PushSubscriptionUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *PushSubscriptionUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// PushSubscriptionCreateBulk is the builder for creating many PushSubscription entities in bulk.
type PushSubscriptionCreateBulk struct {
	config
	err      error
	builders []*PushSubscriptionCreate
	conflict []sql.ConflictOption
}

// Save creates the PushSubscription entities in the database.
func (_c *PushSubscriptionCreateBulk) Save(ctx context.Context) ([]*PushSubscription, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*PushSubscription, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PushSubscriptionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PushSubscriptionCreateBulk) SaveX(ctx context.Context) []*PushSubscription {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PushSubscriptionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PushSubscriptionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PushSubscription.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PushSubscriptionUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *PushSubscriptionCreateBulk) OnConflict(opts ...sql.ConflictOption) *PushSubscriptionUpsertBulk {
	_c.conflict = opts
	return &PushSubscriptionUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PushSubscription.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PushSubscriptionCreateBulk) OnConflictColumns(columns ...string) *PushSubscriptionUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PushSubscriptionUpsertBulk{
		create: _c,
	}
}

// PushSubscriptionUpsertBulk is the builder for "upsert"-ing
// a bulk of PushSubscription nodes.
type PushSubscriptionUpsertBulk struct {
	create *PushSubscriptionCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.PushSubscription.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(pushsubscription.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *PushSubscriptionUpsertBulk) UpdateNewValues() *PushSubscriptionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(pushsubscription.FieldID)
			}
			if _, exists := b.mutation.UserID(); exists {
				s.SetIgnore(pushsubscription.FieldUserID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(pushsubscription.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PushSubscription.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *PushSubscriptionUpsertBulk) Ignore() *PushSubscriptionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PushSubscriptionUpsertBulk) DoNothing() *PushSubscriptionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PushSubscriptionCreateBulk.OnConflict
// documentation for more info.
func (u *PushSubscriptionUpsertBulk) Update(set func(*PushSubscriptionUpsert)) *PushSubscriptionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PushSubscriptionUpsert{UpdateSet: update})
	}))
	return u
}

// SetEndpoint sets the "endpoint" field.
func (u *PushSubscriptionUpsertBulk) SetEndpoint(v string) *PushSubscriptionUpsertBulk {
	return u.Update(func(s *PushSubscriptionUpsert) {
		s.SetEndpoint(v)
	})
}

// UpdateEndpoint sets the "endpoint" field to the value that was provided on create.
func (u *PushSubscriptionUpsertBulk) UpdateEndpoint() *PushSubscriptionUpsertBulk {
	return u.Update(func(s *PushSubscriptionUpsert) {
		s.UpdateEndpoint()
	})
}

// SetP256dh sets the "p256dh" field.
func (u *PushSubscriptionUpsertBulk) SetP256dh(v string) *PushSubscriptionUpsertBulk {
	return u.Update(func(s *PushSubscriptionUpsert) {
		s.SetP256dh(v)
	})
}

// UpdateP256dh sets the "p256dh" field to the value that was provided on create.
func (u *PushSubscriptionUpsertBulk) UpdateP256dh() *PushSubscriptionUpsertBulk {
	return u.Update(func(s *PushSubscriptionUpsert) {
		s.UpdateP256dh()
	})
}

// SetAuth sets the "auth" field.
func (u *PushSubscriptionUpsertBulk) SetAuth(v string) *PushSubscriptionUpsertBulk {
	return u.Update(func(s *PushSubscriptionUpsert) {
		s.SetAuth(v)
	})
}

// UpdateAuth sets the "auth" field to the value that was provided on create.
func (u *PushSubscriptionUpsertBulk) UpdateAuth() *PushSubscriptionUpsertBulk {
	return u.Update(func(s *PushSubscriptionUpsert) {
		s.UpdateAuth()
	})
}

// SetActive sets the "active" field.
func (u *PushSubscriptionUpsertBulk) SetActive(v bool) *PushSubscriptionUpsertBulk {
	return u.Update(func(s *PushSubscriptionUpsert) {
		s.SetActive(v)
	})
}

// UpdateActive sets the "active" field to the value that was provided on create.
func (u *PushSubscriptionUpsertBulk) UpdateActive() *PushSubscriptionUpsertBulk {
	return u.Update(func(s *PushSubscriptionUpsert) {
		s.UpdateActive()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PushSubscriptionUpsertBulk) SetUpdatedAt(v time.Time) *PushSubscriptionUpsertBulk {
	return u.Update(func(s *PushSubscriptionUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PushSubscriptionUpsertBulk) UpdateUpdatedAt() *PushSubscriptionUpsertBulk {
	return u.Update(func(s *PushSubscriptionUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *PushSubscriptionUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the PushSubscriptionCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PushSubscriptionCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PushSubscriptionUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
