// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"regulation/internal/ent/predicate"
	"regulation/internal/ent/rule"
	"regulation/internal/ent/ruleexecution"
	"regulation/internal/ent/savingstransfer"
	"regulation/internal/ent/transaction"
	"regulation/internal/ent/user"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// RuleExecutionUpdate is the builder for updating RuleExecution entities.
type RuleExecutionUpdate struct {
	config
	hooks     []Hook
	mutation  *RuleExecutionMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the RuleExecutionUpdate builder.
func (_u *RuleExecutionUpdate) Where(ps ...predicate.RuleExecution) *RuleExecutionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetRuleID sets the "rule_id" field.
func (_u *RuleExecutionUpdate) SetRuleID(v uuid.UUID) *RuleExecutionUpdate {
	_u.mutation.SetRuleID(v)
	return _u
}

// SetNillableRuleID sets the "rule_id" field if the given value is not nil.
func (_u *RuleExecutionUpdate) SetNillableRuleID(v *uuid.UUID) *RuleExecutionUpdate {
	if v != nil {
		_u.SetRuleID(*v)
	}
	return _u
}

// SetTransactionID sets the "transaction_id" field.
func (_u *RuleExecutionUpdate) SetTransactionID(v uuid.UUID) *RuleExecutionUpdate {
	_u.mutation.SetTransactionID(v)
	return _u
}

// SetNillableTransactionID sets the "transaction_id" field if the given value is not nil.
func (_u *RuleExecutionUpdate) SetNillableTransactionID(v *uuid.UUID) *RuleExecutionUpdate {
	if v != nil {
		_u.SetTransactionID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *RuleExecutionUpdate) SetUserID(v uuid.UUID) *RuleExecutionUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *RuleExecutionUpdate) SetNillableUserID(v *uuid.UUID) *RuleExecutionUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetAmountCents sets the "amount_cents" field.
func (_u *RuleExecutionUpdate) SetAmountCents(v int64) *RuleExecutionUpdate {
	_u.mutation.ResetAmountCents()
	_u.mutation.SetAmountCents(v)
	return _u
}

// SetNillableAmountCents sets the "amount_cents" field if the given value is not nil.
func (_u *RuleExecutionUpdate) SetNillableAmountCents(v *int64) *RuleExecutionUpdate {
	if v != nil {
		_u.SetAmountCents(*v)
	}
	return _u
}

// AddAmountCents adds value to the "amount_cents" field.
func (_u *RuleExecutionUpdate) AddAmountCents(v int64) *RuleExecutionUpdate {
	_u.mutation.AddAmountCents(v)
	return _u
}

// SetSourceAccountID sets the "source_account_id" field.
func (_u *RuleExecutionUpdate) SetSourceAccountID(v uuid.UUID) *RuleExecutionUpdate {
	_u.mutation.SetSourceAccountID(v)
	return _u
}

// SetNillableSourceAccountID sets the "source_account_id" field if the given value is not nil.
func (_u *RuleExecutionUpdate) SetNillableSourceAccountID(v *uuid.UUID) *RuleExecutionUpdate {
	if v != nil {
		_u.SetSourceAccountID(*v)
	}
	return _u
}

// SetTargetAccountID sets the "target_account_id" field.
func (_u *RuleExecutionUpdate) SetTargetAccountID(v uuid.UUID) *RuleExecutionUpdate {
	_u.mutation.SetTargetAccountID(v)
	return _u
}

// SetNillableTargetAccountID sets the "target_account_id" field if the given value is not nil.
func (_u *RuleExecutionUpdate) SetNillableTargetAccountID(v *uuid.UUID) *RuleExecutionUpdate {
	if v != nil {
		_u.SetTargetAccountID(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *RuleExecutionUpdate) SetStatus(v ruleexecution.Status) *RuleExecutionUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *RuleExecutionUpdate) SetNillableStatus(v *ruleexecution.Status) *RuleExecutionUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *RuleExecutionUpdate) SetErrorMessage(v string) *RuleExecutionUpdate {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *RuleExecutionUpdate) SetNillableErrorMessage(v *string) *RuleExecutionUpdate {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (_u *RuleExecutionUpdate) ClearErrorMessage() *RuleExecutionUpdate {
	_u.mutation.ClearErrorMessage()
	return _u
}

// SetCompletedAt sets the "completed_at" field.
func (_u *RuleExecutionUpdate) SetCompletedAt(v time.Time) *RuleExecutionUpdate {
	_u.mutation.SetCompletedAt(v)
	return _u
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_u *RuleExecutionUpdate) SetNillableCompletedAt(v *time.Time) *RuleExecutionUpdate {
	if v != nil {
		_u.SetCompletedAt(*v)
	}
	return _u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (_u *RuleExecutionUpdate) ClearCompletedAt() *RuleExecutionUpdate {
	_u.mutation.ClearCompletedAt()
	return _u
}

// SetRule sets the "rule" edge to the Rule entity.
func (_u *RuleExecutionUpdate) SetRule(v *Rule) *RuleExecutionUpdate {
	return _u.SetRuleID(v.ID)
}

// SetTransaction sets the "transaction" edge to the Transaction entity.
func (_u *RuleExecutionUpdate) SetTransaction(v *Transaction) *RuleExecutionUpdate {
	return _u.SetTransactionID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_u *RuleExecutionUpdate) SetUser(v *User) *RuleExecutionUpdate {
	return _u.SetUserID(v.ID)
}

// SetTransferID sets the "transfer" edge to the SavingsTransfer entity by ID.
func (_u *RuleExecutionUpdate) SetTransferID(id uuid.UUID) *RuleExecutionUpdate {
	_u.mutation.SetTransferID(id)
	return _u
}

// SetNillableTransferID sets the "transfer" edge to the SavingsTransfer entity by ID if the given value is not nil.
func (_u *RuleExecutionUpdate) SetNillableTransferID(id *uuid.UUID) *RuleExecutionUpdate {
	if id != nil {
		_u = _u.SetTransferID(*id)
	}
	return _u
}

// SetTransfer sets the "transfer" edge to the SavingsTransfer entity.
func (_u *RuleExecutionUpdate) SetTransfer(v *SavingsTransfer) *RuleExecutionUpdate {
	return _u.SetTransferID(v.ID)
}

// Mutation returns the RuleExecutionMutation object of the builder.
func (_u *RuleExecutionUpdate) Mutation() *RuleExecutionMutation {
	return _u.mutation
}

// ClearRule clears the "rule" edge to the Rule entity.
func (_u *RuleExecutionUpdate) ClearRule() *RuleExecutionUpdate {
	_u.mutation.ClearRule()
	return _u
}

// ClearTransaction clears the "transaction" edge to the Transaction entity.
func (_u *RuleExecutionUpdate) ClearTransaction() *RuleExecutionUpdate {
	_u.mutation.ClearTransaction()
	return _u
}

// ClearUser clears the "user" edge to the User entity.
func (_u *RuleExecutionUpdate) ClearUser() *RuleExecutionUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearTransfer clears the "transfer" edge to the SavingsTransfer entity.
func (_u *RuleExecutionUpdate) ClearTransfer() *RuleExecutionUpdate {
	_u.mutation.ClearTransfer()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RuleExecutionUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RuleExecutionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RuleExecutionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RuleExecutionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RuleExecutionUpdate) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := ruleexecution.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "RuleExecution.status": %w`, err)}
		}
	}
	if _u.mutation.RuleCleared() && len(_u.mutation.RuleIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "RuleExecution.rule"`)
	}
	if _u.mutation.TransactionCleared() && len(_u.mutation.TransactionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "RuleExecution.transaction"`)
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "RuleExecution.user"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *RuleExecutionUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *RuleExecutionUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *RuleExecutionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(ruleexecution.Table, ruleexecution.Columns, sqlgraph.NewFieldSpec(ruleexecution.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.AmountCents(); ok {
		_spec.SetField(ruleexecution.FieldAmountCents, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAmountCents(); ok {
		_spec.AddField(ruleexecution.FieldAmountCents, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.SourceAccountID(); ok {
		_spec.SetField(ruleexecution.FieldSourceAccountID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.TargetAccountID(); ok {
		_spec.SetField(ruleexecution.FieldTargetAccountID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(ruleexecution.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(ruleexecution.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(ruleexecution.FieldErrorMessage, field.TypeString)
	}
	if value, ok := _u.mutation.CompletedAt(); ok {
		_spec.SetField(ruleexecution.FieldCompletedAt, field.TypeTime, value)
	}
	if _u.mutation.CompletedAtCleared() {
		_spec.ClearField(ruleexecution.FieldCompletedAt, field.TypeTime)
	}
	if _u.mutation.RuleCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ruleexecution.RuleTable,
			Columns: []string{ruleexecution.RuleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rule.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RuleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ruleexecution.RuleTable,
			Columns: []string{ruleexecution.RuleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rule.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TransactionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ruleexecution.TransactionTable,
			Columns: []string{ruleexecution.TransactionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(transaction.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TransactionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ruleexecution.TransactionTable,
			Columns: []string{ruleexecution.TransactionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(transaction.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ruleexecution.UserTable,
			Columns: []string{ruleexecution.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ruleexecution.UserTable,
			Columns: []string{ruleexecution.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TransferCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   ruleexecution.TransferTable,
			Columns: []string{ruleexecution.TransferColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(savingstransfer.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TransferIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   ruleexecution.TransferTable,
			Columns: []string{ruleexecution.TransferColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(savingstransfer.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{ruleexecution.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RuleExecutionUpdateOne is the builder for updating a single RuleExecution entity.
type RuleExecutionUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *RuleExecutionMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetRuleID sets the "rule_id" field.
func (_u *RuleExecutionUpdateOne) SetRuleID(v uuid.UUID) *RuleExecutionUpdateOne {
	_u.mutation.SetRuleID(v)
	return _u
}

// SetNillableRuleID sets the "rule_id" field if the given value is not nil.
func (_u *RuleExecutionUpdateOne) SetNillableRuleID(v *uuid.UUID) *RuleExecutionUpdateOne {
	if v != nil {
		_u.SetRuleID(*v)
	}
	return _u
}

// SetTransactionID sets the "transaction_id" field.
func (_u *RuleExecutionUpdateOne) SetTransactionID(v uuid.UUID) *RuleExecutionUpdateOne {
	_u.mutation.SetTransactionID(v)
	return _u
}

// SetNillableTransactionID sets the "transaction_id" field if the given value is not nil.
func (_u *RuleExecutionUpdateOne) SetNillableTransactionID(v *uuid.UUID) *RuleExecutionUpdateOne {
	if v != nil {
		_u.SetTransactionID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *RuleExecutionUpdateOne) SetUserID(v uuid.UUID) *RuleExecutionUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *RuleExecutionUpdateOne) SetNillableUserID(v *uuid.UUID) *RuleExecutionUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetAmountCents sets the "amount_cents" field.
func (_u *RuleExecutionUpdateOne) SetAmountCents(v int64) *RuleExecutionUpdateOne {
	_u.mutation.ResetAmountCents()
	_u.mutation.SetAmountCents(v)
	return _u
}

// SetNillableAmountCents sets the "amount_cents" field if the given value is not nil.
func (_u *RuleExecutionUpdateOne) SetNillableAmountCents(v *int64) *RuleExecutionUpdateOne {
	if v != nil {
		_u.SetAmountCents(*v)
	}
	return _u
}

// AddAmountCents adds value to the "amount_cents" field.
func (_u *RuleExecutionUpdateOne) AddAmountCents(v int64) *RuleExecutionUpdateOne {
	_u.mutation.AddAmountCents(v)
	return _u
}

// SetSourceAccountID sets the "source_account_id" field.
func (_u *RuleExecutionUpdateOne) SetSourceAccountID(v uuid.UUID) *RuleExecutionUpdateOne {
	_u.mutation.SetSourceAccountID(v)
	return _u
}

// SetNillableSourceAccountID sets the "source_account_id" field if the given value is not nil.
func (_u *RuleExecutionUpdateOne) SetNillableSourceAccountID(v *uuid.UUID) *RuleExecutionUpdateOne {
	if v != nil {
		_u.SetSourceAccountID(*v)
	}
	return _u
}

// SetTargetAccountID sets the "target_account_id" field.
func (_u *RuleExecutionUpdateOne) SetTargetAccountID(v uuid.UUID) *RuleExecutionUpdateOne {
	_u.mutation.SetTargetAccountID(v)
	return _u
}

// SetNillableTargetAccountID sets the "target_account_id" field if the given value is not nil.
func (_u *RuleExecutionUpdateOne) SetNillableTargetAccountID(v *uuid.UUID) *RuleExecutionUpdateOne {
	if v != nil {
		_u.SetTargetAccountID(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *RuleExecutionUpdateOne) SetStatus(v ruleexecution.Status) *RuleExecutionUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *RuleExecutionUpdateOne) SetNillableStatus(v *ruleexecution.Status) *RuleExecutionUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *RuleExecutionUpdateOne) SetErrorMessage(v string) *RuleExecutionUpdateOne {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *RuleExecutionUpdateOne) SetNillableErrorMessage(v *string) *RuleExecutionUpdateOne {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (_u *RuleExecutionUpdateOne) ClearErrorMessage() *RuleExecutionUpdateOne {
	_u.mutation.ClearErrorMessage()
	return _u
}

// SetCompletedAt sets the "completed_at" field.
func (_u *RuleExecutionUpdateOne) SetCompletedAt(v time.Time) *RuleExecutionUpdateOne {
	_u.mutation.SetCompletedAt(v)
	return _u
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_u *RuleExecutionUpdateOne) SetNillableCompletedAt(v *time.Time) *RuleExecutionUpdateOne {
	if v != nil {
		_u.SetCompletedAt(*v)
	}
	return _u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (_u *RuleExecutionUpdateOne) ClearCompletedAt() *RuleExecutionUpdateOne {
	_u.mutation.ClearCompletedAt()
	return _u
}

// SetRule sets the "rule" edge to the Rule entity.
func (_u *RuleExecutionUpdateOne) SetRule(v *Rule) *RuleExecutionUpdateOne {
	return _u.SetRuleID(v.ID)
}

// SetTransaction sets the "transaction" edge to the Transaction entity.
func (_u *RuleExecutionUpdateOne) SetTransaction(v *Transaction) *RuleExecutionUpdateOne {
	return _u.SetTransactionID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_u *RuleExecutionUpdateOne) SetUser(v *User) *RuleExecutionUpdateOne {
	return _u.SetUserID(v.ID)
}

// SetTransferID sets the "transfer" edge to the SavingsTransfer entity by ID.
func (_u *RuleExecutionUpdateOne) SetTransferID(id uuid.UUID) *RuleExecutionUpdateOne {
	_u.mutation.SetTransferID(id)
	return _u
}

// SetNillableTransferID sets the "transfer" edge to the SavingsTransfer entity by ID if the given value is not nil.
func (_u *RuleExecutionUpdateOne) SetNillableTransferID(id *uuid.UUID) *RuleExecutionUpdateOne {
	if id != nil {
		_u = _u.SetTransferID(*id)
	}
	return _u
}

// SetTransfer sets the "transfer" edge to the SavingsTransfer entity.
func (_u *RuleExecutionUpdateOne) SetTransfer(v *SavingsTransfer) *RuleExecutionUpdateOne {
	return _u.SetTransferID(v.ID)
}

// Mutation returns the RuleExecutionMutation object of the builder.
func (_u *RuleExecutionUpdateOne) Mutation() *RuleExecutionMutation {
	return _u.mutation
}

// ClearRule clears the "rule" edge to the Rule entity.
func (_u *RuleExecutionUpdateOne) ClearRule() *RuleExecutionUpdateOne {
	_u.mutation.ClearRule()
	return _u
}

// ClearTransaction clears the "transaction" edge to the Transaction entity.
func (_u *RuleExecutionUpdateOne) ClearTransaction() *RuleExecutionUpdateOne {
	_u.mutation.ClearTransaction()
	return _u
}

// ClearUser clears the "user" edge to the User entity.
func (_u *RuleExecutionUpdateOne) ClearUser() *RuleExecutionUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearTransfer clears the "transfer" edge to the SavingsTransfer entity.
func (_u *RuleExecutionUpdateOne) ClearTransfer() *RuleExecutionUpdateOne {
	_u.mutation.ClearTransfer()
	return _u
}

// Where appends a list predicates to the RuleExecutionUpdate builder.
func (_u *RuleExecutionUpdateOne) Where(ps ...predicate.RuleExecution) *RuleExecutionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RuleExecutionUpdateOne) Select(field string, fields ...string) *RuleExecutionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated RuleExecution entity.
func (_u *RuleExecutionUpdateOne) Save(ctx context.Context) (*RuleExecution, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RuleExecutionUpdateOne) SaveX(ctx context.Context) *RuleExecution {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RuleExecutionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RuleExecutionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RuleExecutionUpdateOne) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := ruleexecution.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "RuleExecution.status": %w`, err)}
		}
	}
	if _u.mutation.RuleCleared() && len(_u.mutation.RuleIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "RuleExecution.rule"`)
	}
	if _u.mutation.TransactionCleared() && len(_u.mutation.TransactionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "RuleExecution.transaction"`)
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "RuleExecution.user"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *RuleExecutionUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *RuleExecutionUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *RuleExecutionUpdateOne) sqlSave(ctx context.Context) (_node *RuleExecution, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(ruleexecution.Table, ruleexecution.Columns, sqlgraph.NewFieldSpec(ruleexecution.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "RuleExecution.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, ruleexecution.FieldID)
		for _, f := range fields {
			if !ruleexecution.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != ruleexecution.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.AmountCents(); ok {
		_spec.SetField(ruleexecution.FieldAmountCents, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAmountCents(); ok {
		_spec.AddField(ruleexecution.FieldAmountCents, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.SourceAccountID(); ok {
		_spec.SetField(ruleexecution.FieldSourceAccountID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.TargetAccountID(); ok {
		_spec.SetField(ruleexecution.FieldTargetAccountID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(ruleexecution.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(ruleexecution.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(ruleexecution.FieldErrorMessage, field.TypeString)
	}
	if value, ok := _u.mutation.CompletedAt(); ok {
		_spec.SetField(ruleexecution.FieldCompletedAt, field.TypeTime, value)
	}
	if _u.mutation.CompletedAtCleared() {
		_spec.ClearField(ruleexecution.FieldCompletedAt, field.TypeTime)
	}
	if _u.mutation.RuleCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ruleexecution.RuleTable,
			Columns: []string{ruleexecution.RuleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rule.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RuleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ruleexecution.RuleTable,
			Columns: []string{ruleexecution.RuleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rule.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TransactionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ruleexecution.TransactionTable,
			Columns: []string{ruleexecution.TransactionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(transaction.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TransactionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ruleexecution.TransactionTable,
			Columns: []string{ruleexecution.TransactionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(transaction.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ruleexecution.UserTable,
			Columns: []string{ruleexecution.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ruleexecution.UserTable,
			Columns: []string{ruleexecution.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TransferCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   ruleexecution.TransferTable,
			Columns: []string{ruleexecution.TransferColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(savingstransfer.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TransferIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   ruleexecution.TransferTable,
			Columns: []string{ruleexecution.TransferColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(savingstransfer.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &RuleExecution{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{ruleexecution.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
