// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"regulation/internal/ent/account"
	"regulation/internal/ent/rule"
	"regulation/internal/ent/user"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// Rule is the model entity for the Rule schema.
type Rule struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// FK to User who owns this rule
	UserID uuid.UUID `json:"user_id,omitempty"`
	// User-friendly rule name (e.g., 'Dining 2x Save')
	Name string `json:"name,omitempty"`
	// Transaction category to match
	Category rule.Category `json:"category,omitempty"`
	// Minimum transaction amount to trigger (cents)
	MinAmountCents *int64 `json:"min_amount_cents,omitempty"`
	// Maximum transaction amount to trigger (cents)
	MaxAmountCents *int64 `json:"max_amount_cents,omitempty"`
	// Type of savings action: multiply transaction amount or fixed amount
	ActionType rule.ActionType `json:"action_type,omitempty"`
	// Multiplier (e.g., 1.5 for 1.5x) or fixed amount in dollars
	ActionValue float64 `json:"action_value,omitempty"`
	// FK to Account where savings should be transferred
	TargetAccountID uuid.UUID `json:"target_account_id,omitempty"`
	// Whether this rule is currently enabled
	IsActive bool `json:"is_active,omitempty"`
	// Rule priority (lower number = higher priority)
	Priority int `json:"priority,omitempty"`
	// Number of times this rule has been triggered
	ExecutionCount int `json:"execution_count,omitempty"`
	// Total amount saved by this rule (cents)
	TotalSavedCents int64 `json:"total_saved_cents,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the RuleQuery when eager-loading is set.
	Edges        RuleEdges `json:"edges"`
	selectValues sql.SelectValues
}

// RuleEdges holds the relations/edges for other nodes in the graph.
type RuleEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// TargetAccount holds the value of the target_account edge.
	TargetAccount *Account `json:"target_account,omitempty"`
	// Executions holds the value of the executions edge.
	Executions []*RuleExecution `json:"executions,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e RuleEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// TargetAccountOrErr returns the TargetAccount value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e RuleEdges) TargetAccountOrErr() (*Account, error) {
	if e.TargetAccount != nil {
		return e.TargetAccount, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: account.Label}
	}
	return nil, &NotLoadedError{edge: "target_account"}
}

// ExecutionsOrErr returns the Executions value or an error if the edge
// was not loaded in eager-loading.
func (e RuleEdges) ExecutionsOrErr() ([]*RuleExecution, error) {
	if e.loadedTypes[2] {
		return e.Executions, nil
	}
	return nil, &NotLoadedError{edge: "executions"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Rule) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case rule.FieldIsActive:
			values[i] = new(sql.NullBool)
		case rule.FieldActionValue:
			values[i] = new(sql.NullFloat64)
		case rule.FieldMinAmountCents, rule.FieldMaxAmountCents, rule.FieldPriority, rule.FieldExecutionCount, rule.FieldTotalSavedCents:
			values[i] = new(sql.NullInt64)
		case rule.FieldName, rule.FieldCategory, rule.FieldActionType:
			values[i] = new(sql.NullString)
		case rule.FieldCreatedAt, rule.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case rule.FieldID, rule.FieldUserID, rule.FieldTargetAccountID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Rule fields.
func (_m *Rule) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case rule.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case rule.FieldUserID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value != nil {
				_m.UserID = *value
			}
		case rule.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case rule.FieldCategory:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field category", values[i])
			} else if value.Valid {
				_m.Category = rule.Category(value.String)
			}
		case rule.FieldMinAmountCents:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field min_amount_cents", values[i])
			} else if value.Valid {
				_m.MinAmountCents = new(int64)
				*_m.MinAmountCents = value.Int64
			}
		case rule.FieldMaxAmountCents:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field max_amount_cents", values[i])
			} else if value.Valid {
				_m.MaxAmountCents = new(int64)
				*_m.MaxAmountCents = value.Int64
			}
		case rule.FieldActionType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field action_type", values[i])
			} else if value.Valid {
				_m.ActionType = rule.ActionType(value.String)
			}
		case rule.FieldActionValue:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field action_value", values[i])
			} else if value.Valid {
				_m.ActionValue = value.Float64
			}
		case rule.FieldTargetAccountID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field target_account_id", values[i])
			} else if value != nil {
				_m.TargetAccountID = *value
			}
		case rule.FieldIsActive:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_active", values[i])
			} else if value.Valid {
				_m.IsActive = value.Bool
			}
		case rule.FieldPriority:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field priority", values[i])
			} else if value.Valid {
				_m.Priority = int(value.Int64)
			}
		case rule.FieldExecutionCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field execution_count", values[i])
			} else if value.Valid {
				_m.ExecutionCount = int(value.Int64)
			}
		case rule.FieldTotalSavedCents:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field total_saved_cents", values[i])
			} else if value.Valid {
				_m.TotalSavedCents = value.Int64
			}
		case rule.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case rule.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Rule.
// This includes values selected through modifiers, order, etc.
func (_m *Rule) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the Rule entity.
func (_m *Rule) QueryUser() *UserQuery {
	return NewRuleClient(_m.config).QueryUser(_m)
}

// QueryTargetAccount queries the "target_account" edge of the Rule entity.
func (_m *Rule) QueryTargetAccount() *AccountQuery {
	return NewRuleClient(_m.config).QueryTargetAccount(_m)
}

// QueryExecutions queries the "executions" edge of the Rule entity.
func (_m *Rule) QueryExecutions() *RuleExecutionQuery {
	return NewRuleClient(_m.config).QueryExecutions(_m)
}

// Update returns a builder for updating this Rule.
// Note that you need to call Rule.Unwrap() before calling this method if this Rule
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Rule) Update() *RuleUpdateOne {
	return NewRuleClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Rule entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Rule) Unwrap() *Rule {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Rule is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Rule) String() string {
	var builder strings.Builder
	builder.WriteString("Rule(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("category=")
	builder.WriteString(fmt.Sprintf("%v", _m.Category))
	builder.WriteString(", ")
	if v := _m.MinAmountCents; v != nil {
		builder.WriteString("min_amount_cents=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.MaxAmountCents; v != nil {
		builder.WriteString("max_amount_cents=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("action_type=")
	builder.WriteString(fmt.Sprintf("%v", _m.ActionType))
	builder.WriteString(", ")
	builder.WriteString("action_value=")
	builder.WriteString(fmt.Sprintf("%v", _m.ActionValue))
	builder.WriteString(", ")
	builder.WriteString("target_account_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.TargetAccountID))
	builder.WriteString(", ")
	builder.WriteString("is_active=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsActive))
	builder.WriteString(", ")
	builder.WriteString("priority=")
	builder.WriteString(fmt.Sprintf("%v", _m.Priority))
	builder.WriteString(", ")
	builder.WriteString("execution_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.ExecutionCount))
	builder.WriteString(", ")
	builder.WriteString("total_saved_cents=")
	builder.WriteString(fmt.Sprintf("%v", _m.TotalSavedCents))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Rules is a parsable slice of Rule.
type Rules []*Rule
