// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"regulation/internal/ent/account"
	"regulation/internal/ent/rule"
	"regulation/internal/ent/ruleexecution"
	"regulation/internal/ent/user"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// RuleCreate is the builder for creating a Rule entity.
type RuleCreate struct {
	config
	mutation *RuleMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetUserID sets the "user_id" field.
func (_c *RuleCreate) SetUserID(v uuid.UUID) *RuleCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetName sets the "name" field.
func (_c *RuleCreate) SetName(v string) *RuleCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetCategory sets the "category" field.
func (_c *RuleCreate) SetCategory(v rule.Category) *RuleCreate {
	_c.mutation.SetCategory(v)
	return _c
}

// SetMinAmountCents sets the "min_amount_cents" field.
func (_c *RuleCreate) SetMinAmountCents(v int64) *RuleCreate {
	_c.mutation.SetMinAmountCents(v)
	return _c
}

// SetNillableMinAmountCents sets the "min_amount_cents" field if the given value is not nil.
func (_c *RuleCreate) SetNillableMinAmountCents(v *int64) *RuleCreate {
	if v != nil {
		_c.SetMinAmountCents(*v)
	}
	return _c
}

// SetMaxAmountCents sets the "max_amount_cents" field.
func (_c *RuleCreate) SetMaxAmountCents(v int64) *RuleCreate {
	_c.mutation.SetMaxAmountCents(v)
	return _c
}

// SetNillableMaxAmountCents sets the "max_amount_cents" field if the given value is not nil.
func (_c *RuleCreate) SetNillableMaxAmountCents(v *int64) *RuleCreate {
	if v != nil {
		_c.SetMaxAmountCents(*v)
	}
	return _c
}

// SetActionType sets the "action_type" field.
func (_c *RuleCreate) SetActionType(v rule.ActionType) *RuleCreate {
	_c.mutation.SetActionType(v)
	return _c
}

// SetActionValue sets the "action_value" field.
func (_c *RuleCreate) SetActionValue(v float64) *RuleCreate {
	_c.mutation.SetActionValue(v)
	return _c
}

// SetTargetAccountID sets the "target_account_id" field.
func (_c *RuleCreate) SetTargetAccountID(v uuid.UUID) *RuleCreate {
	_c.mutation.SetTargetAccountID(v)
	return _c
}

// SetIsActive sets the "is_active" field.
func (_c *RuleCreate) SetIsActive(v bool) *RuleCreate {
	_c.mutation.SetIsActive(v)
	return _c
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_c *RuleCreate) SetNillableIsActive(v *bool) *RuleCreate {
	if v != nil {
		_c.SetIsActive(*v)
	}
	return _c
}

// SetPriority sets the "priority" field.
func (_c *RuleCreate) SetPriority(v int) *RuleCreate {
	_c.mutation.SetPriority(v)
	return _c
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_c *RuleCreate) SetNillablePriority(v *int) *RuleCreate {
	if v != nil {
		_c.SetPriority(*v)
	}
	return _c
}

// SetExecutionCount sets the "execution_count" field.
func (_c *RuleCreate) SetExecutionCount(v int) *RuleCreate {
	_c.mutation.SetExecutionCount(v)
	return _c
}

// SetNillableExecutionCount sets the "execution_count" field if the given value is not nil.
func (_c *RuleCreate) SetNillableExecutionCount(v *int) *RuleCreate {
	if v != nil {
		_c.SetExecutionCount(*v)
	}
	return _c
}

// SetTotalSavedCents sets the "total_saved_cents" field.
func (_c *RuleCreate) SetTotalSavedCents(v int64) *RuleCreate {
	_c.mutation.SetTotalSavedCents(v)
	return _c
}

// SetNillableTotalSavedCents sets the "total_saved_cents" field if the given value is not nil.
func (_c *RuleCreate) SetNillableTotalSavedCents(v *int64) *RuleCreate {
	if v != nil {
		_c.SetTotalSavedCents(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *RuleCreate) SetCreatedAt(v time.Time) *RuleCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *RuleCreate) SetNillableCreatedAt(v *time.Time) *RuleCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *RuleCreate) SetUpdatedAt(v time.Time) *RuleCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *RuleCreate) SetNillableUpdatedAt(v *time.Time) *RuleCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *RuleCreate) SetID(v uuid.UUID) *RuleCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *RuleCreate) SetNillableID(v *uuid.UUID) *RuleCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *RuleCreate) SetUser(v *User) *RuleCreate {
	return _c.SetUserID(v.ID)
}

// SetTargetAccount sets the "target_account" edge to the Account entity.
func (_c *RuleCreate) SetTargetAccount(v *Account) *RuleCreate {
	return _c.SetTargetAccountID(v.ID)
}

// AddExecutionIDs adds the "executions" edge to the RuleExecution entity by IDs.
func (_c *RuleCreate) AddExecutionIDs(ids ...uuid.UUID) *RuleCreate {
	_c.mutation.AddExecutionIDs(ids...)
	return _c
}

// AddExecutions adds the "executions" edges to the RuleExecution entity.
func (_c *RuleCreate) AddExecutions(v ...*RuleExecution) *RuleCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddExecutionIDs(ids...)
}

// Mutation returns the RuleMutation object of the builder.
func (_c *RuleCreate) Mutation() *RuleMutation {
	return _c.mutation
}

// Save creates the Rule in the database.
func (_c *RuleCreate) Save(ctx context.Context) (*Rule, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *RuleCreate) SaveX(ctx context.Context) *Rule {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RuleCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RuleCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *RuleCreate) defaults() {
	if _, ok := _c.mutation.IsActive(); !ok {
		v := rule.DefaultIsActive
		_c.mutation.SetIsActive(v)
	}
	if _, ok := _c.mutation.Priority(); !ok {
		v := rule.DefaultPriority
		_c.mutation.SetPriority(v)
	}
	if _, ok := _c.mutation.ExecutionCount(); !ok {
		v := rule.DefaultExecutionCount
		_c.mutation.SetExecutionCount(v)
	}
	if _, ok := _c.mutation.TotalSavedCents(); !ok {
		v := rule.DefaultTotalSavedCents
		_c.mutation.SetTotalSavedCents(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := rule.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := rule.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := rule.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *RuleCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "Rule.user_id"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Rule.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := rule.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Rule.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Category(); !ok {
		return &ValidationError{Name: "category", err: errors.New(`ent: missing required field "Rule.category"`)}
	}
	if v, ok := _c.mutation.Category(); ok {
		if err := rule.CategoryValidator(v); err != nil {
			return &ValidationError{Name: "category", err: fmt.Errorf(`ent: validator failed for field "Rule.category": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ActionType(); !ok {
		return &ValidationError{Name: "action_type", err: errors.New(`ent: missing required field "Rule.action_type"`)}
	}
	if v, ok := _c.mutation.ActionType(); ok {
		if err := rule.ActionTypeValidator(v); err != nil {
			return &ValidationError{Name: "action_type", err: fmt.Errorf(`ent: validator failed for field "Rule.action_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ActionValue(); !ok {
		return &ValidationError{Name: "action_value", err: errors.New(`ent: missing required field "Rule.action_value"`)}
	}
	if _, ok := _c.mutation.TargetAccountID(); !ok {
		return &ValidationError{Name: "target_account_id", err: errors.New(`ent: missing required field "Rule.target_account_id"`)}
	}
	if _, ok := _c.mutation.IsActive(); !ok {
		return &ValidationError{Name: "is_active", err: errors.New(`ent: missing required field "Rule.is_active"`)}
	}
	if _, ok := _c.mutation.Priority(); !ok {
		return &ValidationError{Name: "priority", err: errors.New(`ent: missing required field "Rule.priority"`)}
	}
	if _, ok := _c.mutation.ExecutionCount(); !ok {
		return &ValidationError{Name: "execution_count", err: errors.New(`ent: missing required field "Rule.execution_count"`)}
	}
	if _, ok := _c.mutation.TotalSavedCents(); !ok {
		return &ValidationError{Name: "total_saved_cents", err: errors.New(`ent: missing required field "Rule.total_saved_cents"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Rule.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Rule.updated_at"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "Rule.user"`)}
	}
	if len(_c.mutation.TargetAccountIDs()) == 0 {
		return &ValidationError{Name: "target_account", err: errors.New(`ent: missing required edge "Rule.target_account"`)}
	}
	return nil
}

func (_c *RuleCreate) sqlSave(ctx context.Context) (*Rule, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *RuleCreate) createSpec() (*Rule, *sqlgraph.CreateSpec) {
	var (
		_node = &Rule{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(rule.Table, sqlgraph.NewFieldSpec(rule.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(rule.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Category(); ok {
		_spec.SetField(rule.FieldCategory, field.TypeEnum, value)
		_node.Category = value
	}
	if value, ok := _c.mutation.MinAmountCents(); ok {
		_spec.SetField(rule.FieldMinAmountCents, field.TypeInt64, value)
		_node.MinAmountCents = &value
	}
	if value, ok := _c.mutation.MaxAmountCents(); ok {
		_spec.SetField(rule.FieldMaxAmountCents, field.TypeInt64, value)
		_node.MaxAmountCents = &value
	}
	if value, ok := _c.mutation.ActionType(); ok {
		_spec.SetField(rule.FieldActionType, field.TypeEnum, value)
		_node.ActionType = value
	}
	if value, ok := _c.mutation.ActionValue(); ok {
		_spec.SetField(rule.FieldActionValue, field.TypeFloat64, value)
		_node.ActionValue = value
	}
	if value, ok := _c.mutation.IsActive(); ok {
		_spec.SetField(rule.FieldIsActive, field.TypeBool, value)
		_node.IsActive = value
	}
	if value, ok := _c.mutation.Priority(); ok {
		_spec.SetField(rule.FieldPriority, field.TypeInt, value)
		_node.Priority = value
	}
	if value, ok := _c.mutation.ExecutionCount(); ok {
		_spec.SetField(rule.FieldExecutionCount, field.TypeInt, value)
		_node.ExecutionCount = value
	}
	if value, ok := _c.mutation.TotalSavedCents(); ok {
		_spec.SetField(rule.FieldTotalSavedCents, field.TypeInt64, value)
		_node.TotalSavedCents = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(rule.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(rule.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   rule.UserTable,
			Columns: []string{rule.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.TargetAccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   rule.TargetAccountTable,
			Columns: []string{rule.TargetAccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.TargetAccountID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ExecutionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   rule.ExecutionsTable,
			Columns: []string{rule.ExecutionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ruleexecution.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Rule.Create().
//		SetUserID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.RuleUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *RuleCreate) OnConflict(opts ...sql.ConflictOption) *RuleUpsertOne {
	_c.conflict = opts
	return &RuleUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Rule.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *RuleCreate) OnConflictColumns(columns ...string) *RuleUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &RuleUpsertOne{
		create: _c,
	}
}

type (
	// RuleUpsertOne is the builder for "upsert"-ing
	//  one Rule node.
	RuleUpsertOne struct {
		create *RuleCreate
	}

	// RuleUpsert is the "OnConflict" setter.
	RuleUpsert struct {
		*sql.UpdateSet
	}
)

// SetUserID sets the "user_id" field.
func (u *RuleUpsert) SetUserID(v uuid.UUID) *RuleUpsert {
	u.Set(rule.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *RuleUpsert) UpdateUserID() *RuleUpsert {
	u.SetExcluded(rule.FieldUserID)
	return u
}

// SetName sets the "name" field.
func (u *RuleUpsert) SetName(v string) *RuleUpsert {
	u.Set(rule.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *RuleUpsert) UpdateName() *RuleUpsert {
	u.SetExcluded(rule.FieldName)
	return u
}

// SetCategory sets the "category" field.
func (u *RuleUpsert) SetCategory(v rule.Category) *RuleUpsert {
	u.Set(rule.FieldCategory, v)
	return u
}

// UpdateCategory sets the "category" field to the value that was provided on create.
func (u *RuleUpsert) UpdateCategory() *RuleUpsert {
	u.SetExcluded(rule.FieldCategory)
	return u
}

// SetMinAmountCents sets the "min_amount_cents" field.
func (u *RuleUpsert) SetMinAmountCents(v int64) *RuleUpsert {
	u.Set(rule.FieldMinAmountCents, v)
	return u
}

// UpdateMinAmountCents sets the "min_amount_cents" field to the value that was provided on create.
func (u *RuleUpsert) UpdateMinAmountCents() *RuleUpsert {
	u.SetExcluded(rule.FieldMinAmountCents)
	return u
}

// AddMinAmountCents adds v to the "min_amount_cents" field.
func (u *RuleUpsert) AddMinAmountCents(v int64) *RuleUpsert {
	u.Add(rule.FieldMinAmountCents, v)
	return u
}

// ClearMinAmountCents clears the value of the "min_amount_cents" field.
func (u *RuleUpsert) ClearMinAmountCents() *RuleUpsert {
	u.SetNull(rule.FieldMinAmountCents)
	return u
}

// SetMaxAmountCents sets the "max_amount_cents" field.
func (u *RuleUpsert) SetMaxAmountCents(v int64) *RuleUpsert {
	u.Set(rule.FieldMaxAmountCents, v)
	return u
}

// UpdateMaxAmountCents sets the "max_amount_cents" field to the value that was provided on create.
func (u *RuleUpsert) UpdateMaxAmountCents() *RuleUpsert {
	u.SetExcluded(rule.FieldMaxAmountCents)
	return u
}

// AddMaxAmountCents adds v to the "max_amount_cents" field.
func (u *RuleUpsert) AddMaxAmountCents(v int64) *RuleUpsert {
	u.Add(rule.FieldMaxAmountCents, v)
	return u
}

// ClearMaxAmountCents clears the value of the "max_amount_cents" field.
func (u *RuleUpsert) ClearMaxAmountCents() *RuleUpsert {
	u.SetNull(rule.FieldMaxAmountCents)
	return u
}

// SetActionType sets the "action_type" field.
func (u *RuleUpsert) SetActionType(v rule.ActionType) *RuleUpsert {
	u.Set(rule.FieldActionType, v)
	return u
}

// UpdateActionType sets the "action_type" field to the value that was provided on create.
func (u *RuleUpsert) UpdateActionType() *RuleUpsert {
	u.SetExcluded(rule.FieldActionType)
	return u
}

// SetActionValue sets the "action_value" field.
func (u *RuleUpsert) SetActionValue(v float64) *RuleUpsert {
	u.Set(rule.FieldActionValue, v)
	return u
}

// UpdateActionValue sets the "action_value" field to the value that was provided on create.
func (u *RuleUpsert) UpdateActionValue() *RuleUpsert {
	u.SetExcluded(rule.FieldActionValue)
	return u
}

// AddActionValue adds v to the "action_value" field.
func (u *RuleUpsert) AddActionValue(v float64) *RuleUpsert {
	u.Add(rule.FieldActionValue, v)
	return u
}

// SetTargetAccountID sets the "target_account_id" field.
func (u *RuleUpsert) SetTargetAccountID(v uuid.UUID) *RuleUpsert {
	u.Set(rule.FieldTargetAccountID, v)
	return u
}

// UpdateTargetAccountID sets the "target_account_id" field to the value that was provided on create.
func (u *RuleUpsert) UpdateTargetAccountID() *RuleUpsert {
	u.SetExcluded(rule.FieldTargetAccountID)
	return u
}

// SetIsActive sets the "is_active" field.
func (u *RuleUpsert) SetIsActive(v bool) *RuleUpsert {
	u.Set(rule.FieldIsActive, v)
	return u
}

// UpdateIsActive sets the "is_active" field to the value that was provided on create.
func (u *RuleUpsert) UpdateIsActive() *RuleUpsert {
	u.SetExcluded(rule.FieldIsActive)
	return u
}

// SetPriority sets the "priority" field.
func (u *RuleUpsert) SetPriority(v int) *RuleUpsert {
	u.Set(rule.FieldPriority, v)
	return u
}

// UpdatePriority sets the "priority" field to the value that was provided on create.
func (u *RuleUpsert) UpdatePriority() *RuleUpsert {
	u.SetExcluded(rule.FieldPriority)
	return u
}

// AddPriority adds v to the "priority" field.
func (u *RuleUpsert) AddPriority(v int) *RuleUpsert {
	u.Add(rule.FieldPriority, v)
	return u
}

// SetExecutionCount sets the "execution_count" field.
func (u *RuleUpsert) SetExecutionCount(v int) *RuleUpsert {
	u.Set(rule.FieldExecutionCount, v)
	return u
}

// UpdateExecutionCount sets the "execution_count" field to the value that was provided on create.
func (u *RuleUpsert) UpdateExecutionCount() *RuleUpsert {
	u.SetExcluded(rule.FieldExecutionCount)
	return u
}

// AddExecutionCount adds v to the "execution_count" field.
func (u *RuleUpsert) AddExecutionCount(v int) *RuleUpsert {
	u.Add(rule.FieldExecutionCount, v)
	return u
}

// SetTotalSavedCents sets the "total_saved_cents" field.
func (u *RuleUpsert) SetTotalSavedCents(v int64) *RuleUpsert {
	u.Set(rule.FieldTotalSavedCents, v)
	return u
}

// UpdateTotalSavedCents sets the "total_saved_cents" field to the value that was provided on create.
func (u *RuleUpsert) UpdateTotalSavedCents() *RuleUpsert {
	u.SetExcluded(rule.FieldTotalSavedCents)
	return u
}

// AddTotalSavedCents adds v to the "total_saved_cents" field.
func (u *RuleUpsert) AddTotalSavedCents(v int64) *RuleUpsert {
	u.Add(rule.FieldTotalSavedCents, v)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *RuleUpsert) SetUpdatedAt(v time.Time) *RuleUpsert {
	u.Set(rule.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *RuleUpsert) UpdateUpdatedAt() *RuleUpsert {
	u.SetExcluded(rule.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Rule.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(rule.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *RuleUpsertOne) UpdateNewValues() *RuleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(rule.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(rule.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Rule.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *RuleUpsertOne) Ignore() *RuleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *RuleUpsertOne) DoNothing() *RuleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the RuleCreate.OnConflict
// documentation for more info.
func (u *RuleUpsertOne) Update(set func(*RuleUpsert)) *RuleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&RuleUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *RuleUpsertOne) SetUserID(v uuid.UUID) *RuleUpsertOne {
	return u.Update(func(s *RuleUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *RuleUpsertOne) UpdateUserID() *RuleUpsertOne {
	return u.Update(func(s *RuleUpsert) {
		s.UpdateUserID()
	})
}

// SetName sets the "name" field.
func (u *RuleUpsertOne) SetName(v string) *RuleUpsertOne {
	return u.Update(func(s *RuleUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *RuleUpsertOne) UpdateName() *RuleUpsertOne {
	return u.Update(func(s *RuleUpsert) {
		s.UpdateName()
	})
}

// SetCategory sets the "category" field.
func (u *RuleUpsertOne) SetCategory(v rule.Category) *RuleUpsertOne {
	return u.Update(func(s *RuleUpsert) {
		s.SetCategory(v)
	})
}

// UpdateCategory sets the "category" field to the value that was provided on create.
func (u *RuleUpsertOne) UpdateCategory() *RuleUpsertOne {
	return u.Update(func(s *RuleUpsert) {
		s.UpdateCategory()
	})
}

// SetMinAmountCents sets the "min_amount_cents" field.
func (u *RuleUpsertOne) SetMinAmountCents(v int64) *RuleUpsertOne {
	return u.Update(func(s *RuleUpsert) {
		s.SetMinAmountCents(v)
	})
}

// AddMinAmountCents adds v to the "min_amount_cents" field.
func (u *RuleUpsertOne) AddMinAmountCents(v int64) *RuleUpsertOne {
	return u.Update(func(s *RuleUpsert) {
		s.AddMinAmountCents(v)
	})
}

// UpdateMinAmountCents sets the "min_amount_cents" field to the value that was provided on create.
func (u *RuleUpsertOne) UpdateMinAmountCents() *RuleUpsertOne {
	return u.Update(func(s *RuleUpsert) {
		s.UpdateMinAmountCents()
	})
}

// ClearMinAmountCents clears the value of the "min_amount_cents" field.
func (u *RuleUpsertOne) ClearMinAmountCents() *RuleUpsertOne {
	return u.Update(func(s *RuleUpsert) {
		s.ClearMinAmountCents()
	})
}

// SetMaxAmountCents sets the "max_amount_cents" field.
func (u *RuleUpsertOne) SetMaxAmountCents(v int64) *RuleUpsertOne {
	return u.Update(func(s *RuleUpsert) {
		s.SetMaxAmountCents(v)
	})
}

// AddMaxAmountCents adds v to the "max_amount_cents" field.
func (u *RuleUpsertOne) AddMaxAmountCents(v int64) *RuleUpsertOne {
	return u.Update(func(s *RuleUpsert) {
		s.AddMaxAmountCents(v)
	})
}

// UpdateMaxAmountCents sets the "max_amount_cents" field to the value that was provided on create.
func (u *RuleUpsertOne) UpdateMaxAmountCents() *RuleUpsertOne {
	return u.Update(func(s *RuleUpsert) {
		s.UpdateMaxAmountCents()
	})
}

// ClearMaxAmountCents clears the value of the "max_amount_cents" field.
func (u *RuleUpsertOne) ClearMaxAmountCents() *RuleUpsertOne {
	return u.Update(func(s *RuleUpsert) {
		s.ClearMaxAmountCents()
	})
}

// SetActionType sets the "action_type" field.
func (u *RuleUpsertOne) SetActionType(v rule.ActionType) *RuleUpsertOne {
	return u.Update(func(s *RuleUpsert) {
		s.SetActionType(v)
	})
}

// UpdateActionType sets the "action_type" field to the value that was provided on create.
func (u *RuleUpsertOne) UpdateActionType() *RuleUpsertOne {
	return u.Update(func(s *RuleUpsert) {
		s.UpdateActionType()
	})
}

// SetActionValue sets the "action_value" field.
func (u *RuleUpsertOne) SetActionValue(v float64) *RuleUpsertOne {
	return u.Update(func(s *RuleUpsert) {
		s.SetActionValue(v)
	})
}

// AddActionValue adds v to the "action_value" field.
func (u *RuleUpsertOne) AddActionValue(v float64) *RuleUpsertOne {
	return u.Update(func(s *RuleUpsert) {
		s.AddActionValue(v)
	})
}

// UpdateActionValue sets the "action_value" field to the value that was provided on create.
func (u *RuleUpsertOne) UpdateActionValue() *RuleUpsertOne {
	return u.Update(func(s *RuleUpsert) {
		s.UpdateActionValue()
	})
}

// SetTargetAccountID sets the "target_account_id" field.
func (u *RuleUpsertOne) SetTargetAccountID(v uuid.UUID) *RuleUpsertOne {
	return u.Update(func(s *RuleUpsert) {
		s.SetTargetAccountID(v)
	})
}

// UpdateTargetAccountID sets the "target_account_id" field to the value that was provided on create.
func (u *RuleUpsertOne) UpdateTargetAccountID() *RuleUpsertOne {
	return u.Update(func(s *RuleUpsert) {
		s.UpdateTargetAccountID()
	})
}

// SetIsActive sets the "is_active" field.
func (u *RuleUpsertOne) SetIsActive(v bool) *RuleUpsertOne {
	return u.Update(func(s *RuleUpsert) {
		s.SetIsActive(v)
	})
}

// UpdateIsActive sets the "is_active" field to the value that was provided on create.
func (u *RuleUpsertOne) UpdateIsActive() *RuleUpsertOne {
	return u.Update(func(s *RuleUpsert) {
		s.UpdateIsActive()
	})
}

// SetPriority sets the "priority" field.
func (u *RuleUpsertOne) SetPriority(v int) *RuleUpsertOne {
	return u.Update(func(s *RuleUpsert) {
		s.SetPriority(v)
	})
}

// AddPriority adds v to the "priority" field.
func (u *RuleUpsertOne) AddPriority(v int) *RuleUpsertOne {
	return u.Update(func(s *RuleUpsert) {
		s.AddPriority(v)
	})
}

// UpdatePriority sets the "priority" field to the value that was provided on create.
func (u *RuleUpsertOne) UpdatePriority() *RuleUpsertOne {
	return u.Update(func(s *RuleUpsert) {
		s.UpdatePriority()
	})
}

// SetExecutionCount sets the "execution_count" field.
func (u *RuleUpsertOne) SetExecutionCount(v int) *RuleUpsertOne {
	return u.Update(func(s *RuleUpsert) {
		s.SetExecutionCount(v)
	})
}

// AddExecutionCount adds v to the "execution_count" field.
func (u *RuleUpsertOne) AddExecutionCount(v int) *RuleUpsertOne {
	return u.Update(func(s *RuleUpsert) {
		s.AddExecutionCount(v)
	})
}

// UpdateExecutionCount sets the "execution_count" field to the value that was provided on create.
func (u *RuleUpsertOne) UpdateExecutionCount() *RuleUpsertOne {
	return u.Update(func(s *RuleUpsert) {
		s.UpdateExecutionCount()
	})
}

// SetTotalSavedCents sets the "total_saved_cents" field.
func (u *RuleUpsertOne) SetTotalSavedCents(v int64) *RuleUpsertOne {
	return u.Update(func(s *RuleUpsert) {
		s.SetTotalSavedCents(v)
	})
}

// AddTotalSavedCents adds v to the "total_saved_cents" field.
func (u *RuleUpsertOne) AddTotalSavedCents(v int64) *RuleUpsertOne {
	return u.Update(func(s *RuleUpsert) {
		s.AddTotalSavedCents(v)
	})
}

// UpdateTotalSavedCents sets the "total_saved_cents" field to the value that was provided on create.
func (u *RuleUpsertOne) UpdateTotalSavedCents() *RuleUpsertOne {
	return u.Update(func(s *RuleUpsert) {
		s.UpdateTotalSavedCents()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *RuleUpsertOne) SetUpdatedAt(v time.Time) *RuleUpsertOne {
	return u.Update(func(s *RuleUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *RuleUpsertOne) UpdateUpdatedAt() *RuleUpsertOne {
	return u.Update(func(s *RuleUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *RuleUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for RuleCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *RuleUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *RuleUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: RuleUpsertOne.ID is not supported by MySQL driver. Use RuleUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *RuleUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// RuleCreateBulk is the builder for creating many Rule entities in bulk.
type RuleCreateBulk struct {
	config
	err      error
	builders []*RuleCreate
	conflict []sql.ConflictOption
}

// Save creates the Rule entities in the database.
func (_c *RuleCreateBulk) Save(ctx context.Context) ([]*Rule, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Rule, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RuleMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *RuleCreateBulk) SaveX(ctx context.Context) []*Rule {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RuleCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RuleCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Rule.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.RuleUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *RuleCreateBulk) OnConflict(opts ...sql.ConflictOption) *RuleUpsertBulk {
	_c.conflict = opts
	return &RuleUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Rule.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *RuleCreateBulk) OnConflictColumns(columns ...string) *RuleUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &RuleUpsertBulk{
		create: _c,
	}
}

// RuleUpsertBulk is the builder for "upsert"-ing
// a bulk of Rule nodes.
type RuleUpsertBulk struct {
	create *RuleCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Rule.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(rule.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *RuleUpsertBulk) UpdateNewValues() *RuleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(rule.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(rule.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Rule.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *RuleUpsertBulk) Ignore() *RuleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *RuleUpsertBulk) DoNothing() *RuleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the RuleCreateBulk.OnConflict
// documentation for more info.
func (u *RuleUpsertBulk) Update(set func(*RuleUpsert)) *RuleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&RuleUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *RuleUpsertBulk) SetUserID(v uuid.UUID) *RuleUpsertBulk {
	return u.Update(func(s *RuleUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *RuleUpsertBulk) UpdateUserID() *RuleUpsertBulk {
	return u.Update(func(s *RuleUpsert) {
		s.UpdateUserID()
	})
}

// SetName sets the "name" field.
func (u *RuleUpsertBulk) SetName(v string) *RuleUpsertBulk {
	return u.Update(func(s *RuleUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *RuleUpsertBulk) UpdateName() *RuleUpsertBulk {
	return u.Update(func(s *RuleUpsert) {
		s.UpdateName()
	})
}

// SetCategory sets the "category" field.
func (u *RuleUpsertBulk) SetCategory(v rule.Category) *RuleUpsertBulk {
	return u.Update(func(s *RuleUpsert) {
		s.SetCategory(v)
	})
}

// UpdateCategory sets the "category" field to the value that was provided on create.
func (u *RuleUpsertBulk) UpdateCategory() *RuleUpsertBulk {
	return u.Update(func(s *RuleUpsert) {
		s.UpdateCategory()
	})
}

// SetMinAmountCents sets the "min_amount_cents" field.
func (u *RuleUpsertBulk) SetMinAmountCents(v int64) *RuleUpsertBulk {
	return u.Update(func(s *RuleUpsert) {
		s.SetMinAmountCents(v)
	})
}

// AddMinAmountCents adds v to the "min_amount_cents" field.
func (u *RuleUpsertBulk) AddMinAmountCents(v int64) *RuleUpsertBulk {
	return u.Update(func(s *RuleUpsert) {
		s.AddMinAmountCents(v)
	})
}

// UpdateMinAmountCents sets the "min_amount_cents" field to the value that was provided on create.
func (u *RuleUpsertBulk) UpdateMinAmountCents() *RuleUpsertBulk {
	return u.Update(func(s *RuleUpsert) {
		s.UpdateMinAmountCents()
	})
}

// ClearMinAmountCents clears the value of the "min_amount_cents" field.
func (u *RuleUpsertBulk) ClearMinAmountCents() *RuleUpsertBulk {
	return u.Update(func(s *RuleUpsert) {
		s.ClearMinAmountCents()
	})
}

// SetMaxAmountCents sets the "max_amount_cents" field.
func (u *RuleUpsertBulk) SetMaxAmountCents(v int64) *RuleUpsertBulk {
	return u.Update(func(s *RuleUpsert) {
		s.SetMaxAmountCents(v)
	})
}

// AddMaxAmountCents adds v to the "max_amount_cents" field.
func (u *RuleUpsertBulk) AddMaxAmountCents(v int64) *RuleUpsertBulk {
	return u.Update(func(s *RuleUpsert) {
		s.AddMaxAmountCents(v)
	})
}

// UpdateMaxAmountCents sets the "max_amount_cents" field to the value that was provided on create.
func (u *RuleUpsertBulk) UpdateMaxAmountCents() *RuleUpsertBulk {
	return u.Update(func(s *RuleUpsert) {
		s.UpdateMaxAmountCents()
	})
}

// ClearMaxAmountCents clears the value of the "max_amount_cents" field.
func (u *RuleUpsertBulk) ClearMaxAmountCents() *RuleUpsertBulk {
	return u.Update(func(s *RuleUpsert) {
		s.ClearMaxAmountCents()
	})
}

// SetActionType sets the "action_type" field.
func (u *RuleUpsertBulk) SetActionType(v rule.ActionType) *RuleUpsertBulk {
	return u.Update(func(s *RuleUpsert) {
		s.SetActionType(v)
	})
}

// UpdateActionType sets the "action_type" field to the value that was provided on create.
func (u *RuleUpsertBulk) UpdateActionType() *RuleUpsertBulk {
	return u.Update(func(s *RuleUpsert) {
		s.UpdateActionType()
	})
}

// SetActionValue sets the "action_value" field.
func (u *RuleUpsertBulk) SetActionValue(v float64) *RuleUpsertBulk {
	return u.Update(func(s *RuleUpsert) {
		s.SetActionValue(v)
	})
}

// AddActionValue adds v to the "action_value" field.
func (u *RuleUpsertBulk) AddActionValue(v float64) *RuleUpsertBulk {
	return u.Update(func(s *RuleUpsert) {
		s.AddActionValue(v)
	})
}

// UpdateActionValue sets the "action_value" field to the value that was provided on create.
func (u *RuleUpsertBulk) UpdateActionValue() *RuleUpsertBulk {
	return u.Update(func(s *RuleUpsert) {
		s.UpdateActionValue()
	})
}

// SetTargetAccountID sets the "target_account_id" field.
func (u *RuleUpsertBulk) SetTargetAccountID(v uuid.UUID) *RuleUpsertBulk {
	return u.Update(func(s *RuleUpsert) {
		s.SetTargetAccountID(v)
	})
}

// UpdateTargetAccountID sets the "target_account_id" field to the value that was provided on create.
func (u *RuleUpsertBulk) UpdateTargetAccountID() *RuleUpsertBulk {
	return u.Update(func(s *RuleUpsert) {
		s.UpdateTargetAccountID()
	})
}

// SetIsActive sets the "is_active" field.
func (u *RuleUpsertBulk) SetIsActive(v bool) *RuleUpsertBulk {
	return u.Update(func(s *RuleUpsert) {
		s.SetIsActive(v)
	})
}

// UpdateIsActive sets the "is_active" field to the value that was provided on create.
func (u *RuleUpsertBulk) UpdateIsActive() *RuleUpsertBulk {
	return u.Update(func(s *RuleUpsert) {
		s.UpdateIsActive()
	})
}

// SetPriority sets the "priority" field.
func (u *RuleUpsertBulk) SetPriority(v int) *RuleUpsertBulk {
	return u.Update(func(s *RuleUpsert) {
		s.SetPriority(v)
	})
}

// AddPriority adds v to the "priority" field.
func (u *RuleUpsertBulk) AddPriority(v int) *RuleUpsertBulk {
	return u.Update(func(s *RuleUpsert) {
		s.AddPriority(v)
	})
}

// UpdatePriority sets the "priority" field to the value that was provided on create.
func (u *RuleUpsertBulk) UpdatePriority() *RuleUpsertBulk {
	return u.Update(func(s *RuleUpsert) {
		s.UpdatePriority()
	})
}

// SetExecutionCount sets the "execution_count" field.
func (u *RuleUpsertBulk) SetExecutionCount(v int) *RuleUpsertBulk {
	return u.Update(func(s *RuleUpsert) {
		s.SetExecutionCount(v)
	})
}

// AddExecutionCount adds v to the "execution_count" field.
func (u *RuleUpsertBulk) AddExecutionCount(v int) *RuleUpsertBulk {
	return u.Update(func(s *RuleUpsert) {
		s.AddExecutionCount(v)
	})
}

// UpdateExecutionCount sets the "execution_count" field to the value that was provided on create.
func (u *RuleUpsertBulk) UpdateExecutionCount() *RuleUpsertBulk {
	return u.Update(func(s *RuleUpsert) {
		s.UpdateExecutionCount()
	})
}

// SetTotalSavedCents sets the "total_saved_cents" field.
func (u *RuleUpsertBulk) SetTotalSavedCents(v int64) *RuleUpsertBulk {
	return u.Update(func(s *RuleUpsert) {
		s.SetTotalSavedCents(v)
	})
}

// AddTotalSavedCents adds v to the "total_saved_cents" field.
func (u *RuleUpsertBulk) AddTotalSavedCents(v int64) *RuleUpsertBulk {
	return u.Update(func(s *RuleUpsert) {
		s.AddTotalSavedCents(v)
	})
}

// UpdateTotalSavedCents sets the "total_saved_cents" field to the value that was provided on create.
func (u *RuleUpsertBulk) UpdateTotalSavedCents() *RuleUpsertBulk {
	return u.Update(func(s *RuleUpsert) {
		s.UpdateTotalSavedCents()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *RuleUpsertBulk) SetUpdatedAt(v time.Time) *RuleUpsertBulk {
	return u.Update(func(s *RuleUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *RuleUpsertBulk) UpdateUpdatedAt() *RuleUpsertBulk {
	return u.Update(func(s *RuleUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *RuleUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the RuleCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for RuleCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *RuleUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
