// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"regulation/internal/ent/account"
	"regulation/internal/ent/ruleexecution"
	"regulation/internal/ent/savingstransfer"
	"regulation/internal/ent/user"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// SavingsTransfer is the model entity for the SavingsTransfer schema.
type SavingsTransfer struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// FK to RuleExecution that created this transfer
	RuleExecutionID uuid.UUID `json:"rule_execution_id,omitempty"`
	// FK to User
	UserID uuid.UUID `json:"user_id,omitempty"`
	// FK to Account (checking)
	SourceAccountID uuid.UUID `json:"source_account_id,omitempty"`
	// FK to Account (savings)
	TargetAccountID uuid.UUID `json:"target_account_id,omitempty"`
	// Amount to transfer in cents
	AmountCents int64 `json:"amount_cents,omitempty"`
	// Transfer status
	Status savingstransfer.Status `json:"status,omitempty"`
	// Plaid transfer ID if real transfer was executed
	PlaidTransferID string `json:"plaid_transfer_id,omitempty"`
	// Error details if failed
	ErrorMessage string `json:"error_message,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// When transfer was executed
	ExecutedAt *time.Time `json:"executed_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the SavingsTransferQuery when eager-loading is set.
	Edges        SavingsTransferEdges `json:"edges"`
	selectValues sql.SelectValues
}

// SavingsTransferEdges holds the relations/edges for other nodes in the graph.
type SavingsTransferEdges struct {
	// RuleExecution holds the value of the rule_execution edge.
	RuleExecution *RuleExecution `json:"rule_execution,omitempty"`
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// SourceAccount holds the value of the source_account edge.
	SourceAccount *Account `json:"source_account,omitempty"`
	// TargetAccount holds the value of the target_account edge.
	TargetAccount *Account `json:"target_account,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [4]bool
}

// RuleExecutionOrErr returns the RuleExecution value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SavingsTransferEdges) RuleExecutionOrErr() (*RuleExecution, error) {
	if e.RuleExecution != nil {
		return e.RuleExecution, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: ruleexecution.Label}
	}
	return nil, &NotLoadedError{edge: "rule_execution"}
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SavingsTransferEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// SourceAccountOrErr returns the SourceAccount value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SavingsTransferEdges) SourceAccountOrErr() (*Account, error) {
	if e.SourceAccount != nil {
		return e.SourceAccount, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: account.Label}
	}
	return nil, &NotLoadedError{edge: "source_account"}
}

// TargetAccountOrErr returns the TargetAccount value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SavingsTransferEdges) TargetAccountOrErr() (*Account, error) {
	if e.TargetAccount != nil {
		return e.TargetAccount, nil
	} else if e.loadedTypes[3] {
		return nil, &NotFoundError{label: account.Label}
	}
	return nil, &NotLoadedError{edge: "target_account"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SavingsTransfer) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case savingstransfer.FieldAmountCents:
			values[i] = new(sql.NullInt64)
		case savingstransfer.FieldStatus, savingstransfer.FieldPlaidTransferID, savingstransfer.FieldErrorMessage:
			values[i] = new(sql.NullString)
		case savingstransfer.FieldCreatedAt, savingstransfer.FieldExecutedAt:
			values[i] = new(sql.NullTime)
		case savingstransfer.FieldID, savingstransfer.FieldRuleExecutionID, savingstransfer.FieldUserID, savingstransfer.FieldSourceAccountID, savingstransfer.FieldTargetAccountID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SavingsTransfer fields.
func (_m *SavingsTransfer) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case savingstransfer.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case savingstransfer.FieldRuleExecutionID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field rule_execution_id", values[i])
			} else if value != nil {
				_m.RuleExecutionID = *value
			}
		case savingstransfer.FieldUserID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value != nil {
				_m.UserID = *value
			}
		case savingstransfer.FieldSourceAccountID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field source_account_id", values[i])
			} else if value != nil {
				_m.SourceAccountID = *value
			}
		case savingstransfer.FieldTargetAccountID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field target_account_id", values[i])
			} else if value != nil {
				_m.TargetAccountID = *value
			}
		case savingstransfer.FieldAmountCents:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field amount_cents", values[i])
			} else if value.Valid {
				_m.AmountCents = value.Int64
			}
		case savingstransfer.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = savingstransfer.Status(value.String)
			}
		case savingstransfer.FieldPlaidTransferID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field plaid_transfer_id", values[i])
			} else if value.Valid {
				_m.PlaidTransferID = value.String
			}
		case savingstransfer.FieldErrorMessage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error_message", values[i])
			} else if value.Valid {
				_m.ErrorMessage = value.String
			}
		case savingstransfer.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case savingstransfer.FieldExecutedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field executed_at", values[i])
			} else if value.Valid {
				_m.ExecutedAt = new(time.Time)
				*_m.ExecutedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the SavingsTransfer.
// This includes values selected through modifiers, order, etc.
func (_m *SavingsTransfer) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryRuleExecution queries the "rule_execution" edge of the SavingsTransfer entity.
func (_m *SavingsTransfer) QueryRuleExecution() *RuleExecutionQuery {
	return NewSavingsTransferClient(_m.config).QueryRuleExecution(_m)
}

// QueryUser queries the "user" edge of the SavingsTransfer entity.
func (_m *SavingsTransfer) QueryUser() *UserQuery {
	return NewSavingsTransferClient(_m.config).QueryUser(_m)
}

// QuerySourceAccount queries the "source_account" edge of the SavingsTransfer entity.
func (_m *SavingsTransfer) QuerySourceAccount() *AccountQuery {
	return NewSavingsTransferClient(_m.config).QuerySourceAccount(_m)
}

// QueryTargetAccount queries the "target_account" edge of the SavingsTransfer entity.
func (_m *SavingsTransfer) QueryTargetAccount() *AccountQuery {
	return NewSavingsTransferClient(_m.config).QueryTargetAccount(_m)
}

// Update returns a builder for updating this SavingsTransfer.
// Note that you need to call SavingsTransfer.Unwrap() before calling this method if this SavingsTransfer
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *SavingsTransfer) Update() *SavingsTransferUpdateOne {
	return NewSavingsTransferClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the SavingsTransfer entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *SavingsTransfer) Unwrap() *SavingsTransfer {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: SavingsTransfer is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *SavingsTransfer) String() string {
	var builder strings.Builder
	builder.WriteString("SavingsTransfer(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("rule_execution_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.RuleExecutionID))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("source_account_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.SourceAccountID))
	builder.WriteString(", ")
	builder.WriteString("target_account_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.TargetAccountID))
	builder.WriteString(", ")
	builder.WriteString("amount_cents=")
	builder.WriteString(fmt.Sprintf("%v", _m.AmountCents))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("plaid_transfer_id=")
	builder.WriteString(_m.PlaidTransferID)
	builder.WriteString(", ")
	builder.WriteString("error_message=")
	builder.WriteString(_m.ErrorMessage)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.ExecutedAt; v != nil {
		builder.WriteString("executed_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// SavingsTransfers is a parsable slice of SavingsTransfer.
type SavingsTransfers []*SavingsTransfer
