// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"regulation/internal/ent/predicate"
	"regulation/internal/ent/savingstransfer"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SavingsTransferDelete is the builder for deleting a SavingsTransfer entity.
type SavingsTransferDelete struct {
	config
	hooks    []Hook
	mutation *SavingsTransferMutation
}

// Where appends a list predicates to the SavingsTransferDelete builder.
func (_d *SavingsTransferDelete) Where(ps ...predicate.SavingsTransfer) *SavingsTransferDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *SavingsTransferDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *SavingsTransferDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *SavingsTransferDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(savingstransfer.Table, sqlgraph.NewFieldSpec(savingstransfer.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// SavingsTransferDeleteOne is the builder for deleting a single SavingsTransfer entity.
type SavingsTransferDeleteOne struct {
	_d *SavingsTransferDelete
}

// Where appends a list predicates to the SavingsTransferDelete builder.
func (_d *SavingsTransferDeleteOne) Where(ps ...predicate.SavingsTransfer) *SavingsTransferDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *SavingsTransferDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{savingstransfer.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *SavingsTransferDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
