// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"regulation/internal/ent/account"
	"regulation/internal/ent/predicate"
	"regulation/internal/ent/ruleexecution"
	"regulation/internal/ent/savingstransfer"
	"regulation/internal/ent/user"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// SavingsTransferUpdate is the builder for updating SavingsTransfer entities.
type SavingsTransferUpdate struct {
	config
	hooks     []Hook
	mutation  *SavingsTransferMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the SavingsTransferUpdate builder.
func (_u *SavingsTransferUpdate) Where(ps ...predicate.SavingsTransfer) *SavingsTransferUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetRuleExecutionID sets the "rule_execution_id" field.
func (_u *SavingsTransferUpdate) SetRuleExecutionID(v uuid.UUID) *SavingsTransferUpdate {
	_u.mutation.SetRuleExecutionID(v)
	return _u
}

// SetNillableRuleExecutionID sets the "rule_execution_id" field if the given value is not nil.
func (_u *SavingsTransferUpdate) SetNillableRuleExecutionID(v *uuid.UUID) *SavingsTransferUpdate {
	if v != nil {
		_u.SetRuleExecutionID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *SavingsTransferUpdate) SetUserID(v uuid.UUID) *SavingsTransferUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *SavingsTransferUpdate) SetNillableUserID(v *uuid.UUID) *SavingsTransferUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetSourceAccountID sets the "source_account_id" field.
func (_u *SavingsTransferUpdate) SetSourceAccountID(v uuid.UUID) *SavingsTransferUpdate {
	_u.mutation.SetSourceAccountID(v)
	return _u
}

// SetNillableSourceAccountID sets the "source_account_id" field if the given value is not nil.
func (_u *SavingsTransferUpdate) SetNillableSourceAccountID(v *uuid.UUID) *SavingsTransferUpdate {
	if v != nil {
		_u.SetSourceAccountID(*v)
	}
	return _u
}

// SetTargetAccountID sets the "target_account_id" field.
func (_u *SavingsTransferUpdate) SetTargetAccountID(v uuid.UUID) *SavingsTransferUpdate {
	_u.mutation.SetTargetAccountID(v)
	return _u
}

// SetNillableTargetAccountID sets the "target_account_id" field if the given value is not nil.
func (_u *SavingsTransferUpdate) SetNillableTargetAccountID(v *uuid.UUID) *SavingsTransferUpdate {
	if v != nil {
		_u.SetTargetAccountID(*v)
	}
	return _u
}

// SetAmountCents sets the "amount_cents" field.
func (_u *SavingsTransferUpdate) SetAmountCents(v int64) *SavingsTransferUpdate {
	_u.mutation.ResetAmountCents()
	_u.mutation.SetAmountCents(v)
	return _u
}

// SetNillableAmountCents sets the "amount_cents" field if the given value is not nil.
func (_u *SavingsTransferUpdate) SetNillableAmountCents(v *int64) *SavingsTransferUpdate {
	if v != nil {
		_u.SetAmountCents(*v)
	}
	return _u
}

// AddAmountCents adds value to the "amount_cents" field.
func (_u *SavingsTransferUpdate) AddAmountCents(v int64) *SavingsTransferUpdate {
	_u.mutation.AddAmountCents(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *SavingsTransferUpdate) SetStatus(v savingstransfer.Status) *SavingsTransferUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SavingsTransferUpdate) SetNillableStatus(v *savingstransfer.Status) *SavingsTransferUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetPlaidTransferID sets the "plaid_transfer_id" field.
func (_u *SavingsTransferUpdate) SetPlaidTransferID(v string) *SavingsTransferUpdate {
	_u.mutation.SetPlaidTransferID(v)
	return _u
}

// SetNillablePlaidTransferID sets the "plaid_transfer_id" field if the given value is not nil.
func (_u *SavingsTransferUpdate) SetNillablePlaidTransferID(v *string) *SavingsTransferUpdate {
	if v != nil {
		_u.SetPlaidTransferID(*v)
	}
	return _u
}

// ClearPlaidTransferID clears the value of the "plaid_transfer_id" field.
func (_u *SavingsTransferUpdate) ClearPlaidTransferID() *SavingsTransferUpdate {
	_u.mutation.ClearPlaidTransferID()
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *SavingsTransferUpdate) SetErrorMessage(v string) *SavingsTransferUpdate {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *SavingsTransferUpdate) SetNillableErrorMessage(v *string) *SavingsTransferUpdate {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (_u *SavingsTransferUpdate) ClearErrorMessage() *SavingsTransferUpdate {
	_u.mutation.ClearErrorMessage()
	return _u
}

// SetExecutedAt sets the "executed_at" field.
func (_u *SavingsTransferUpdate) SetExecutedAt(v time.Time) *SavingsTransferUpdate {
	_u.mutation.SetExecutedAt(v)
	return _u
}

// SetNillableExecutedAt sets the "executed_at" field if the given value is not nil.
func (_u *SavingsTransferUpdate) SetNillableExecutedAt(v *time.Time) *SavingsTransferUpdate {
	if v != nil {
		_u.SetExecutedAt(*v)
	}
	return _u
}

// ClearExecutedAt clears the value of the "executed_at" field.
func (_u *SavingsTransferUpdate) ClearExecutedAt() *SavingsTransferUpdate {
	_u.mutation.ClearExecutedAt()
	return _u
}

// SetRuleExecution sets the "rule_execution" edge to the RuleExecution entity.
func (_u *SavingsTransferUpdate) SetRuleExecution(v *RuleExecution) *SavingsTransferUpdate {
	return _u.SetRuleExecutionID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_u *SavingsTransferUpdate) SetUser(v *User) *SavingsTransferUpdate {
	return _u.SetUserID(v.ID)
}

// SetSourceAccount sets the "source_account" edge to the Account entity.
func (_u *SavingsTransferUpdate) SetSourceAccount(v *Account) *SavingsTransferUpdate {
	return _u.SetSourceAccountID(v.ID)
}

// SetTargetAccount sets the "target_account" edge to the Account entity.
func (_u *SavingsTransferUpdate) SetTargetAccount(v *Account) *SavingsTransferUpdate {
	return _u.SetTargetAccountID(v.ID)
}

// Mutation returns the SavingsTransferMutation object of the builder.
func (_u *SavingsTransferUpdate) Mutation() *SavingsTransferMutation {
	return _u.mutation
}

// ClearRuleExecution clears the "rule_execution" edge to the RuleExecution entity.
func (_u *SavingsTransferUpdate) ClearRuleExecution() *SavingsTransferUpdate {
	_u.mutation.ClearRuleExecution()
	return _u
}

// ClearUser clears the "user" edge to the User entity.
func (_u *SavingsTransferUpdate) ClearUser() *SavingsTransferUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearSourceAccount clears the "source_account" edge to the Account entity.
func (_u *SavingsTransferUpdate) ClearSourceAccount() *SavingsTransferUpdate {
	_u.mutation.ClearSourceAccount()
	return _u
}

// ClearTargetAccount clears the "target_account" edge to the Account entity.
func (_u *SavingsTransferUpdate) ClearTargetAccount() *SavingsTransferUpdate {
	_u.mutation.ClearTargetAccount()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SavingsTransferUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SavingsTransferUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SavingsTransferUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SavingsTransferUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SavingsTransferUpdate) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := savingstransfer.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "SavingsTransfer.status": %w`, err)}
		}
	}
	if _u.mutation.RuleExecutionCleared() && len(_u.mutation.RuleExecutionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SavingsTransfer.rule_execution"`)
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SavingsTransfer.user"`)
	}
	if _u.mutation.SourceAccountCleared() && len(_u.mutation.SourceAccountIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SavingsTransfer.source_account"`)
	}
	if _u.mutation.TargetAccountCleared() && len(_u.mutation.TargetAccountIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SavingsTransfer.target_account"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *SavingsTransferUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *SavingsTransferUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *SavingsTransferUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(savingstransfer.Table, savingstransfer.Columns, sqlgraph.NewFieldSpec(savingstransfer.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.AmountCents(); ok {
		_spec.SetField(savingstransfer.FieldAmountCents, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAmountCents(); ok {
		_spec.AddField(savingstransfer.FieldAmountCents, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(savingstransfer.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.PlaidTransferID(); ok {
		_spec.SetField(savingstransfer.FieldPlaidTransferID, field.TypeString, value)
	}
	if _u.mutation.PlaidTransferIDCleared() {
		_spec.ClearField(savingstransfer.FieldPlaidTransferID, field.TypeString)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(savingstransfer.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(savingstransfer.FieldErrorMessage, field.TypeString)
	}
	if value, ok := _u.mutation.ExecutedAt(); ok {
		_spec.SetField(savingstransfer.FieldExecutedAt, field.TypeTime, value)
	}
	if _u.mutation.ExecutedAtCleared() {
		_spec.ClearField(savingstransfer.FieldExecutedAt, field.TypeTime)
	}
	if _u.mutation.RuleExecutionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   savingstransfer.RuleExecutionTable,
			Columns: []string{savingstransfer.RuleExecutionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ruleexecution.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RuleExecutionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   savingstransfer.RuleExecutionTable,
			Columns: []string{savingstransfer.RuleExecutionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ruleexecution.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   savingstransfer.UserTable,
			Columns: []string{savingstransfer.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   savingstransfer.UserTable,
			Columns: []string{savingstransfer.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SourceAccountCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   savingstransfer.SourceAccountTable,
			Columns: []string{savingstransfer.SourceAccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SourceAccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   savingstransfer.SourceAccountTable,
			Columns: []string{savingstransfer.SourceAccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TargetAccountCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   savingstransfer.TargetAccountTable,
			Columns: []string{savingstransfer.TargetAccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TargetAccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   savingstransfer.TargetAccountTable,
			Columns: []string{savingstransfer.TargetAccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{savingstransfer.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SavingsTransferUpdateOne is the builder for updating a single SavingsTransfer entity.
type SavingsTransferUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *SavingsTransferMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetRuleExecutionID sets the "rule_execution_id" field.
func (_u *SavingsTransferUpdateOne) SetRuleExecutionID(v uuid.UUID) *SavingsTransferUpdateOne {
	_u.mutation.SetRuleExecutionID(v)
	return _u
}

// SetNillableRuleExecutionID sets the "rule_execution_id" field if the given value is not nil.
func (_u *SavingsTransferUpdateOne) SetNillableRuleExecutionID(v *uuid.UUID) *SavingsTransferUpdateOne {
	if v != nil {
		_u.SetRuleExecutionID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *SavingsTransferUpdateOne) SetUserID(v uuid.UUID) *SavingsTransferUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *SavingsTransferUpdateOne) SetNillableUserID(v *uuid.UUID) *SavingsTransferUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetSourceAccountID sets the "source_account_id" field.
func (_u *SavingsTransferUpdateOne) SetSourceAccountID(v uuid.UUID) *SavingsTransferUpdateOne {
	_u.mutation.SetSourceAccountID(v)
	return _u
}

// SetNillableSourceAccountID sets the "source_account_id" field if the given value is not nil.
func (_u *SavingsTransferUpdateOne) SetNillableSourceAccountID(v *uuid.UUID) *SavingsTransferUpdateOne {
	if v != nil {
		_u.SetSourceAccountID(*v)
	}
	return _u
}

// SetTargetAccountID sets the "target_account_id" field.
func (_u *SavingsTransferUpdateOne) SetTargetAccountID(v uuid.UUID) *SavingsTransferUpdateOne {
	_u.mutation.SetTargetAccountID(v)
	return _u
}

// SetNillableTargetAccountID sets the "target_account_id" field if the given value is not nil.
func (_u *SavingsTransferUpdateOne) SetNillableTargetAccountID(v *uuid.UUID) *SavingsTransferUpdateOne {
	if v != nil {
		_u.SetTargetAccountID(*v)
	}
	return _u
}

// SetAmountCents sets the "amount_cents" field.
func (_u *SavingsTransferUpdateOne) SetAmountCents(v int64) *SavingsTransferUpdateOne {
	_u.mutation.ResetAmountCents()
	_u.mutation.SetAmountCents(v)
	return _u
}

// SetNillableAmountCents sets the "amount_cents" field if the given value is not nil.
func (_u *SavingsTransferUpdateOne) SetNillableAmountCents(v *int64) *SavingsTransferUpdateOne {
	if v != nil {
		_u.SetAmountCents(*v)
	}
	return _u
}

// AddAmountCents adds value to the "amount_cents" field.
func (_u *SavingsTransferUpdateOne) AddAmountCents(v int64) *SavingsTransferUpdateOne {
	_u.mutation.AddAmountCents(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *SavingsTransferUpdateOne) SetStatus(v savingstransfer.Status) *SavingsTransferUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SavingsTransferUpdateOne) SetNillableStatus(v *savingstransfer.Status) *SavingsTransferUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetPlaidTransferID sets the "plaid_transfer_id" field.
func (_u *SavingsTransferUpdateOne) SetPlaidTransferID(v string) *SavingsTransferUpdateOne {
	_u.mutation.SetPlaidTransferID(v)
	return _u
}

// SetNillablePlaidTransferID sets the "plaid_transfer_id" field if the given value is not nil.
func (_u *SavingsTransferUpdateOne) SetNillablePlaidTransferID(v *string) *SavingsTransferUpdateOne {
	if v != nil {
		_u.SetPlaidTransferID(*v)
	}
	return _u
}

// ClearPlaidTransferID clears the value of the "plaid_transfer_id" field.
func (_u *SavingsTransferUpdateOne) ClearPlaidTransferID() *SavingsTransferUpdateOne {
	_u.mutation.ClearPlaidTransferID()
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *SavingsTransferUpdateOne) SetErrorMessage(v string) *SavingsTransferUpdateOne {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *SavingsTransferUpdateOne) SetNillableErrorMessage(v *string) *SavingsTransferUpdateOne {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (_u *SavingsTransferUpdateOne) ClearErrorMessage() *SavingsTransferUpdateOne {
	_u.mutation.ClearErrorMessage()
	return _u
}

// SetExecutedAt sets the "executed_at" field.
func (_u *SavingsTransferUpdateOne) SetExecutedAt(v time.Time) *SavingsTransferUpdateOne {
	_u.mutation.SetExecutedAt(v)
	return _u
}

// SetNillableExecutedAt sets the "executed_at" field if the given value is not nil.
func (_u *SavingsTransferUpdateOne) SetNillableExecutedAt(v *time.Time) *SavingsTransferUpdateOne {
	if v != nil {
		_u.SetExecutedAt(*v)
	}
	return _u
}

// ClearExecutedAt clears the value of the "executed_at" field.
func (_u *SavingsTransferUpdateOne) ClearExecutedAt() *SavingsTransferUpdateOne {
	_u.mutation.ClearExecutedAt()
	return _u
}

// SetRuleExecution sets the "rule_execution" edge to the RuleExecution entity.
func (_u *SavingsTransferUpdateOne) SetRuleExecution(v *RuleExecution) *SavingsTransferUpdateOne {
	return _u.SetRuleExecutionID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_u *SavingsTransferUpdateOne) SetUser(v *User) *SavingsTransferUpdateOne {
	return _u.SetUserID(v.ID)
}

// SetSourceAccount sets the "source_account" edge to the Account entity.
func (_u *SavingsTransferUpdateOne) SetSourceAccount(v *Account) *SavingsTransferUpdateOne {
	return _u.SetSourceAccountID(v.ID)
}

// SetTargetAccount sets the "target_account" edge to the Account entity.
func (_u *SavingsTransferUpdateOne) SetTargetAccount(v *Account) *SavingsTransferUpdateOne {
	return _u.SetTargetAccountID(v.ID)
}

// Mutation returns the SavingsTransferMutation object of the builder.
func (_u *SavingsTransferUpdateOne) Mutation() *SavingsTransferMutation {
	return _u.mutation
}

// ClearRuleExecution clears the "rule_execution" edge to the RuleExecution entity.
func (_u *SavingsTransferUpdateOne) ClearRuleExecution() *SavingsTransferUpdateOne {
	_u.mutation.ClearRuleExecution()
	return _u
}

// ClearUser clears the "user" edge to the User entity.
func (_u *SavingsTransferUpdateOne) ClearUser() *SavingsTransferUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearSourceAccount clears the "source_account" edge to the Account entity.
func (_u *SavingsTransferUpdateOne) ClearSourceAccount() *SavingsTransferUpdateOne {
	_u.mutation.ClearSourceAccount()
	return _u
}

// ClearTargetAccount clears the "target_account" edge to the Account entity.
func (_u *SavingsTransferUpdateOne) ClearTargetAccount() *SavingsTransferUpdateOne {
	_u.mutation.ClearTargetAccount()
	return _u
}

// Where appends a list predicates to the SavingsTransferUpdate builder.
func (_u *SavingsTransferUpdateOne) Where(ps ...predicate.SavingsTransfer) *SavingsTransferUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SavingsTransferUpdateOne) Select(field string, fields ...string) *SavingsTransferUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SavingsTransfer entity.
func (_u *SavingsTransferUpdateOne) Save(ctx context.Context) (*SavingsTransfer, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SavingsTransferUpdateOne) SaveX(ctx context.Context) *SavingsTransfer {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SavingsTransferUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SavingsTransferUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SavingsTransferUpdateOne) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := savingstransfer.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "SavingsTransfer.status": %w`, err)}
		}
	}
	if _u.mutation.RuleExecutionCleared() && len(_u.mutation.RuleExecutionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SavingsTransfer.rule_execution"`)
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SavingsTransfer.user"`)
	}
	if _u.mutation.SourceAccountCleared() && len(_u.mutation.SourceAccountIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SavingsTransfer.source_account"`)
	}
	if _u.mutation.TargetAccountCleared() && len(_u.mutation.TargetAccountIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SavingsTransfer.target_account"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *SavingsTransferUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *SavingsTransferUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *SavingsTransferUpdateOne) sqlSave(ctx context.Context) (_node *SavingsTransfer, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(savingstransfer.Table, savingstransfer.Columns, sqlgraph.NewFieldSpec(savingstransfer.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SavingsTransfer.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, savingstransfer.FieldID)
		for _, f := range fields {
			if !savingstransfer.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != savingstransfer.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.AmountCents(); ok {
		_spec.SetField(savingstransfer.FieldAmountCents, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAmountCents(); ok {
		_spec.AddField(savingstransfer.FieldAmountCents, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(savingstransfer.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.PlaidTransferID(); ok {
		_spec.SetField(savingstransfer.FieldPlaidTransferID, field.TypeString, value)
	}
	if _u.mutation.PlaidTransferIDCleared() {
		_spec.ClearField(savingstransfer.FieldPlaidTransferID, field.TypeString)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(savingstransfer.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(savingstransfer.FieldErrorMessage, field.TypeString)
	}
	if value, ok := _u.mutation.ExecutedAt(); ok {
		_spec.SetField(savingstransfer.FieldExecutedAt, field.TypeTime, value)
	}
	if _u.mutation.ExecutedAtCleared() {
		_spec.ClearField(savingstransfer.FieldExecutedAt, field.TypeTime)
	}
	if _u.mutation.RuleExecutionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   savingstransfer.RuleExecutionTable,
			Columns: []string{savingstransfer.RuleExecutionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ruleexecution.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RuleExecutionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   savingstransfer.RuleExecutionTable,
			Columns: []string{savingstransfer.RuleExecutionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ruleexecution.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   savingstransfer.UserTable,
			Columns: []string{savingstransfer.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   savingstransfer.UserTable,
			Columns: []string{savingstransfer.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SourceAccountCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   savingstransfer.SourceAccountTable,
			Columns: []string{savingstransfer.SourceAccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SourceAccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   savingstransfer.SourceAccountTable,
			Columns: []string{savingstransfer.SourceAccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TargetAccountCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   savingstransfer.TargetAccountTable,
			Columns: []string{savingstransfer.TargetAccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TargetAccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   savingstransfer.TargetAccountTable,
			Columns: []string{savingstransfer.TargetAccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &SavingsTransfer{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{savingstransfer.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
