// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"regulation/internal/ent/account"
	"regulation/internal/ent/predicate"
	"regulation/internal/ent/ruleexecution"
	"regulation/internal/ent/transaction"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// TransactionUpdate is the builder for updating Transaction entities.
type TransactionUpdate struct {
	config
	hooks     []Hook
	mutation  *TransactionMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the TransactionUpdate builder.
func (_u *TransactionUpdate) Where(ps ...predicate.Transaction) *TransactionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *TransactionUpdate) SetAccountID(v uuid.UUID) *TransactionUpdate {
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *TransactionUpdate) SetNillableAccountID(v *uuid.UUID) *TransactionUpdate {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// SetPlaidID sets the "plaid_id" field.
func (_u *TransactionUpdate) SetPlaidID(v string) *TransactionUpdate {
	_u.mutation.SetPlaidID(v)
	return _u
}

// SetNillablePlaidID sets the "plaid_id" field if the given value is not nil.
func (_u *TransactionUpdate) SetNillablePlaidID(v *string) *TransactionUpdate {
	if v != nil {
		_u.SetPlaidID(*v)
	}
	return _u
}

// SetAmount sets the "amount" field.
func (_u *TransactionUpdate) SetAmount(v int64) *TransactionUpdate {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *TransactionUpdate) SetNillableAmount(v *int64) *TransactionUpdate {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *TransactionUpdate) AddAmount(v int64) *TransactionUpdate {
	_u.mutation.AddAmount(v)
	return _u
}

// SetDate sets the "date" field.
func (_u *TransactionUpdate) SetDate(v time.Time) *TransactionUpdate {
	_u.mutation.SetDate(v)
	return _u
}

// SetNillableDate sets the "date" field if the given value is not nil.
func (_u *TransactionUpdate) SetNillableDate(v *time.Time) *TransactionUpdate {
	if v != nil {
		_u.SetDate(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *TransactionUpdate) SetName(v string) *TransactionUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *TransactionUpdate) SetNillableName(v *string) *TransactionUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetMerchantName sets the "merchant_name" field.
func (_u *TransactionUpdate) SetMerchantName(v string) *TransactionUpdate {
	_u.mutation.SetMerchantName(v)
	return _u
}

// SetNillableMerchantName sets the "merchant_name" field if the given value is not nil.
func (_u *TransactionUpdate) SetNillableMerchantName(v *string) *TransactionUpdate {
	if v != nil {
		_u.SetMerchantName(*v)
	}
	return _u
}

// ClearMerchantName clears the value of the "merchant_name" field.
func (_u *TransactionUpdate) ClearMerchantName() *TransactionUpdate {
	_u.mutation.ClearMerchantName()
	return _u
}

// SetCategory sets the "category" field.
func (_u *TransactionUpdate) SetCategory(v string) *TransactionUpdate {
	_u.mutation.SetCategory(v)
	return _u
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (_u *TransactionUpdate) SetNillableCategory(v *string) *TransactionUpdate {
	if v != nil {
		_u.SetCategory(*v)
	}
	return _u
}

// SetPlaidCategories sets the "plaid_categories" field.
func (_u *TransactionUpdate) SetPlaidCategories(v []string) *TransactionUpdate {
	_u.mutation.SetPlaidCategories(v)
	return _u
}

// AppendPlaidCategories appends value to the "plaid_categories" field.
func (_u *TransactionUpdate) AppendPlaidCategories(v []string) *TransactionUpdate {
	_u.mutation.AppendPlaidCategories(v)
	return _u
}

// ClearPlaidCategories clears the value of the "plaid_categories" field.
func (_u *TransactionUpdate) ClearPlaidCategories() *TransactionUpdate {
	_u.mutation.ClearPlaidCategories()
	return _u
}

// SetPending sets the "pending" field.
func (_u *TransactionUpdate) SetPending(v bool) *TransactionUpdate {
	_u.mutation.SetPending(v)
	return _u
}

// SetNillablePending sets the "pending" field if the given value is not nil.
func (_u *TransactionUpdate) SetNillablePending(v *bool) *TransactionUpdate {
	if v != nil {
		_u.SetPending(*v)
	}
	return _u
}

// SetPaymentChannel sets the "payment_channel" field.
func (_u *TransactionUpdate) SetPaymentChannel(v string) *TransactionUpdate {
	_u.mutation.SetPaymentChannel(v)
	return _u
}

// SetNillablePaymentChannel sets the "payment_channel" field if the given value is not nil.
func (_u *TransactionUpdate) SetNillablePaymentChannel(v *string) *TransactionUpdate {
	if v != nil {
		_u.SetPaymentChannel(*v)
	}
	return _u
}

// ClearPaymentChannel clears the value of the "payment_channel" field.
func (_u *TransactionUpdate) ClearPaymentChannel() *TransactionUpdate {
	_u.mutation.ClearPaymentChannel()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TransactionUpdate) SetUpdatedAt(v time.Time) *TransactionUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetAccount sets the "account" edge to the Account entity.
func (_u *TransactionUpdate) SetAccount(v *Account) *TransactionUpdate {
	return _u.SetAccountID(v.ID)
}

// AddRuleExecutionIDs adds the "rule_executions" edge to the RuleExecution entity by IDs.
func (_u *TransactionUpdate) AddRuleExecutionIDs(ids ...uuid.UUID) *TransactionUpdate {
	_u.mutation.AddRuleExecutionIDs(ids...)
	return _u
}

// AddRuleExecutions adds the "rule_executions" edges to the RuleExecution entity.
func (_u *TransactionUpdate) AddRuleExecutions(v ...*RuleExecution) *TransactionUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRuleExecutionIDs(ids...)
}

// Mutation returns the TransactionMutation object of the builder.
func (_u *TransactionUpdate) Mutation() *TransactionMutation {
	return _u.mutation
}

// ClearAccount clears the "account" edge to the Account entity.
func (_u *TransactionUpdate) ClearAccount() *TransactionUpdate {
	_u.mutation.ClearAccount()
	return _u
}

// ClearRuleExecutions clears all "rule_executions" edges to the RuleExecution entity.
func (_u *TransactionUpdate) ClearRuleExecutions() *TransactionUpdate {
	_u.mutation.ClearRuleExecutions()
	return _u
}

// RemoveRuleExecutionIDs removes the "rule_executions" edge to RuleExecution entities by IDs.
func (_u *TransactionUpdate) RemoveRuleExecutionIDs(ids ...uuid.UUID) *TransactionUpdate {
	_u.mutation.RemoveRuleExecutionIDs(ids...)
	return _u
}

// RemoveRuleExecutions removes "rule_executions" edges to RuleExecution entities.
func (_u *TransactionUpdate) RemoveRuleExecutions(v ...*RuleExecution) *TransactionUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRuleExecutionIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TransactionUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TransactionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TransactionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TransactionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TransactionUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := transaction.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TransactionUpdate) check() error {
	if v, ok := _u.mutation.PlaidID(); ok {
		if err := transaction.PlaidIDValidator(v); err != nil {
			return &ValidationError{Name: "plaid_id", err: fmt.Errorf(`ent: validator failed for field "Transaction.plaid_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := transaction.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Transaction.name": %w`, err)}
		}
	}
	if _u.mutation.AccountCleared() && len(_u.mutation.AccountIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Transaction.account"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *TransactionUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *TransactionUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *TransactionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(transaction.Table, transaction.Columns, sqlgraph.NewFieldSpec(transaction.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.PlaidID(); ok {
		_spec.SetField(transaction.FieldPlaidID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(transaction.FieldAmount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(transaction.FieldAmount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Date(); ok {
		_spec.SetField(transaction.FieldDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(transaction.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.MerchantName(); ok {
		_spec.SetField(transaction.FieldMerchantName, field.TypeString, value)
	}
	if _u.mutation.MerchantNameCleared() {
		_spec.ClearField(transaction.FieldMerchantName, field.TypeString)
	}
	if value, ok := _u.mutation.Category(); ok {
		_spec.SetField(transaction.FieldCategory, field.TypeString, value)
	}
	if value, ok := _u.mutation.PlaidCategories(); ok {
		_spec.SetField(transaction.FieldPlaidCategories, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedPlaidCategories(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, transaction.FieldPlaidCategories, value)
		})
	}
	if _u.mutation.PlaidCategoriesCleared() {
		_spec.ClearField(transaction.FieldPlaidCategories, field.TypeJSON)
	}
	if value, ok := _u.mutation.Pending(); ok {
		_spec.SetField(transaction.FieldPending, field.TypeBool, value)
	}
	if value, ok := _u.mutation.PaymentChannel(); ok {
		_spec.SetField(transaction.FieldPaymentChannel, field.TypeString, value)
	}
	if _u.mutation.PaymentChannelCleared() {
		_spec.ClearField(transaction.FieldPaymentChannel, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(transaction.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.AccountCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   transaction.AccountTable,
			Columns: []string{transaction.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   transaction.AccountTable,
			Columns: []string{transaction.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RuleExecutionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   transaction.RuleExecutionsTable,
			Columns: []string{transaction.RuleExecutionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ruleexecution.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRuleExecutionsIDs(); len(nodes) > 0 && !_u.mutation.RuleExecutionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   transaction.RuleExecutionsTable,
			Columns: []string{transaction.RuleExecutionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ruleexecution.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RuleExecutionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   transaction.RuleExecutionsTable,
			Columns: []string{transaction.RuleExecutionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ruleexecution.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{transaction.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TransactionUpdateOne is the builder for updating a single Transaction entity.
type TransactionUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *TransactionMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetAccountID sets the "account_id" field.
func (_u *TransactionUpdateOne) SetAccountID(v uuid.UUID) *TransactionUpdateOne {
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *TransactionUpdateOne) SetNillableAccountID(v *uuid.UUID) *TransactionUpdateOne {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// SetPlaidID sets the "plaid_id" field.
func (_u *TransactionUpdateOne) SetPlaidID(v string) *TransactionUpdateOne {
	_u.mutation.SetPlaidID(v)
	return _u
}

// SetNillablePlaidID sets the "plaid_id" field if the given value is not nil.
func (_u *TransactionUpdateOne) SetNillablePlaidID(v *string) *TransactionUpdateOne {
	if v != nil {
		_u.SetPlaidID(*v)
	}
	return _u
}

// SetAmount sets the "amount" field.
func (_u *TransactionUpdateOne) SetAmount(v int64) *TransactionUpdateOne {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *TransactionUpdateOne) SetNillableAmount(v *int64) *TransactionUpdateOne {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *TransactionUpdateOne) AddAmount(v int64) *TransactionUpdateOne {
	_u.mutation.AddAmount(v)
	return _u
}

// SetDate sets the "date" field.
func (_u *TransactionUpdateOne) SetDate(v time.Time) *TransactionUpdateOne {
	_u.mutation.SetDate(v)
	return _u
}

// SetNillableDate sets the "date" field if the given value is not nil.
func (_u *TransactionUpdateOne) SetNillableDate(v *time.Time) *TransactionUpdateOne {
	if v != nil {
		_u.SetDate(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *TransactionUpdateOne) SetName(v string) *TransactionUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *TransactionUpdateOne) SetNillableName(v *string) *TransactionUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetMerchantName sets the "merchant_name" field.
func (_u *TransactionUpdateOne) SetMerchantName(v string) *TransactionUpdateOne {
	_u.mutation.SetMerchantName(v)
	return _u
}

// SetNillableMerchantName sets the "merchant_name" field if the given value is not nil.
func (_u *TransactionUpdateOne) SetNillableMerchantName(v *string) *TransactionUpdateOne {
	if v != nil {
		_u.SetMerchantName(*v)
	}
	return _u
}

// ClearMerchantName clears the value of the "merchant_name" field.
func (_u *TransactionUpdateOne) ClearMerchantName() *TransactionUpdateOne {
	_u.mutation.ClearMerchantName()
	return _u
}

// SetCategory sets the "category" field.
func (_u *TransactionUpdateOne) SetCategory(v string) *TransactionUpdateOne {
	_u.mutation.SetCategory(v)
	return _u
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (_u *TransactionUpdateOne) SetNillableCategory(v *string) *TransactionUpdateOne {
	if v != nil {
		_u.SetCategory(*v)
	}
	return _u
}

// SetPlaidCategories sets the "plaid_categories" field.
func (_u *TransactionUpdateOne) SetPlaidCategories(v []string) *TransactionUpdateOne {
	_u.mutation.SetPlaidCategories(v)
	return _u
}

// AppendPlaidCategories appends value to the "plaid_categories" field.
func (_u *TransactionUpdateOne) AppendPlaidCategories(v []string) *TransactionUpdateOne {
	_u.mutation.AppendPlaidCategories(v)
	return _u
}

// ClearPlaidCategories clears the value of the "plaid_categories" field.
func (_u *TransactionUpdateOne) ClearPlaidCategories() *TransactionUpdateOne {
	_u.mutation.ClearPlaidCategories()
	return _u
}

// SetPending sets the "pending" field.
func (_u *TransactionUpdateOne) SetPending(v bool) *TransactionUpdateOne {
	_u.mutation.SetPending(v)
	return _u
}

// SetNillablePending sets the "pending" field if the given value is not nil.
func (_u *TransactionUpdateOne) SetNillablePending(v *bool) *TransactionUpdateOne {
	if v != nil {
		_u.SetPending(*v)
	}
	return _u
}

// SetPaymentChannel sets the "payment_channel" field.
func (_u *TransactionUpdateOne) SetPaymentChannel(v string) *TransactionUpdateOne {
	_u.mutation.SetPaymentChannel(v)
	return _u
}

// SetNillablePaymentChannel sets the "payment_channel" field if the given value is not nil.
func (_u *TransactionUpdateOne) SetNillablePaymentChannel(v *string) *TransactionUpdateOne {
	if v != nil {
		_u.SetPaymentChannel(*v)
	}
	return _u
}

// ClearPaymentChannel clears the value of the "payment_channel" field.
func (_u *TransactionUpdateOne) ClearPaymentChannel() *TransactionUpdateOne {
	_u.mutation.ClearPaymentChannel()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TransactionUpdateOne) SetUpdatedAt(v time.Time) *TransactionUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetAccount sets the "account" edge to the Account entity.
func (_u *TransactionUpdateOne) SetAccount(v *Account) *TransactionUpdateOne {
	return _u.SetAccountID(v.ID)
}

// AddRuleExecutionIDs adds the "rule_executions" edge to the RuleExecution entity by IDs.
func (_u *TransactionUpdateOne) AddRuleExecutionIDs(ids ...uuid.UUID) *TransactionUpdateOne {
	_u.mutation.AddRuleExecutionIDs(ids...)
	return _u
}

// AddRuleExecutions adds the "rule_executions" edges to the RuleExecution entity.
func (_u *TransactionUpdateOne) AddRuleExecutions(v ...*RuleExecution) *TransactionUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRuleExecutionIDs(ids...)
}

// Mutation returns the TransactionMutation object of the builder.
func (_u *TransactionUpdateOne) Mutation() *TransactionMutation {
	return _u.mutation
}

// ClearAccount clears the "account" edge to the Account entity.
func (_u *TransactionUpdateOne) ClearAccount() *TransactionUpdateOne {
	_u.mutation.ClearAccount()
	return _u
}

// ClearRuleExecutions clears all "rule_executions" edges to the RuleExecution entity.
func (_u *TransactionUpdateOne) ClearRuleExecutions() *TransactionUpdateOne {
	_u.mutation.ClearRuleExecutions()
	return _u
}

// RemoveRuleExecutionIDs removes the "rule_executions" edge to RuleExecution entities by IDs.
func (_u *TransactionUpdateOne) RemoveRuleExecutionIDs(ids ...uuid.UUID) *TransactionUpdateOne {
	_u.mutation.RemoveRuleExecutionIDs(ids...)
	return _u
}

// RemoveRuleExecutions removes "rule_executions" edges to RuleExecution entities.
func (_u *TransactionUpdateOne) RemoveRuleExecutions(v ...*RuleExecution) *TransactionUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRuleExecutionIDs(ids...)
}

// Where appends a list predicates to the TransactionUpdate builder.
func (_u *TransactionUpdateOne) Where(ps ...predicate.Transaction) *TransactionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TransactionUpdateOne) Select(field string, fields ...string) *TransactionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Transaction entity.
func (_u *TransactionUpdateOne) Save(ctx context.Context) (*Transaction, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TransactionUpdateOne) SaveX(ctx context.Context) *Transaction {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TransactionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TransactionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TransactionUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := transaction.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TransactionUpdateOne) check() error {
	if v, ok := _u.mutation.PlaidID(); ok {
		if err := transaction.PlaidIDValidator(v); err != nil {
			return &ValidationError{Name: "plaid_id", err: fmt.Errorf(`ent: validator failed for field "Transaction.plaid_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := transaction.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Transaction.name": %w`, err)}
		}
	}
	if _u.mutation.AccountCleared() && len(_u.mutation.AccountIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Transaction.account"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *TransactionUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *TransactionUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *TransactionUpdateOne) sqlSave(ctx context.Context) (_node *Transaction, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(transaction.Table, transaction.Columns, sqlgraph.NewFieldSpec(transaction.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Transaction.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, transaction.FieldID)
		for _, f := range fields {
			if !transaction.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != transaction.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.PlaidID(); ok {
		_spec.SetField(transaction.FieldPlaidID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(transaction.FieldAmount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(transaction.FieldAmount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Date(); ok {
		_spec.SetField(transaction.FieldDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(transaction.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.MerchantName(); ok {
		_spec.SetField(transaction.FieldMerchantName, field.TypeString, value)
	}
	if _u.mutation.MerchantNameCleared() {
		_spec.ClearField(transaction.FieldMerchantName, field.TypeString)
	}
	if value, ok := _u.mutation.Category(); ok {
		_spec.SetField(transaction.FieldCategory, field.TypeString, value)
	}
	if value, ok := _u.mutation.PlaidCategories(); ok {
		_spec.SetField(transaction.FieldPlaidCategories, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedPlaidCategories(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, transaction.FieldPlaidCategories, value)
		})
	}
	if _u.mutation.PlaidCategoriesCleared() {
		_spec.ClearField(transaction.FieldPlaidCategories, field.TypeJSON)
	}
	if value, ok := _u.mutation.Pending(); ok {
		_spec.SetField(transaction.FieldPending, field.TypeBool, value)
	}
	if value, ok := _u.mutation.PaymentChannel(); ok {
		_spec.SetField(transaction.FieldPaymentChannel, field.TypeString, value)
	}
	if _u.mutation.PaymentChannelCleared() {
		_spec.ClearField(transaction.FieldPaymentChannel, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(transaction.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.AccountCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   transaction.AccountTable,
			Columns: []string{transaction.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   transaction.AccountTable,
			Columns: []string{transaction.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RuleExecutionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   transaction.RuleExecutionsTable,
			Columns: []string{transaction.RuleExecutionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ruleexecution.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRuleExecutionsIDs(); len(nodes) > 0 && !_u.mutation.RuleExecutionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   transaction.RuleExecutionsTable,
			Columns: []string{transaction.RuleExecutionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ruleexecution.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RuleExecutionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   transaction.RuleExecutionsTable,
			Columns: []string{transaction.RuleExecutionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ruleexecution.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &Transaction{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{transaction.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
