// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"regulation/internal/ent/predicate"
	"regulation/internal/ent/virtualaccount"
	"regulation/internal/ent/virtualaccounttransaction"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// VirtualAccountTransactionUpdate is the builder for updating VirtualAccountTransaction entities.
type VirtualAccountTransactionUpdate struct {
	config
	hooks     []Hook
	mutation  *VirtualAccountTransactionMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the VirtualAccountTransactionUpdate builder.
func (_u *VirtualAccountTransactionUpdate) Where(ps ...predicate.VirtualAccountTransaction) *VirtualAccountTransactionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetAdjustedDollars sets the "adjusted_dollars" field.
func (_u *VirtualAccountTransactionUpdate) SetAdjustedDollars(v int) *VirtualAccountTransactionUpdate {
	_u.mutation.ResetAdjustedDollars()
	_u.mutation.SetAdjustedDollars(v)
	return _u
}

// SetNillableAdjustedDollars sets the "adjusted_dollars" field if the given value is not nil.
func (_u *VirtualAccountTransactionUpdate) SetNillableAdjustedDollars(v *int) *VirtualAccountTransactionUpdate {
	if v != nil {
		_u.SetAdjustedDollars(*v)
	}
	return _u
}

// AddAdjustedDollars adds value to the "adjusted_dollars" field.
func (_u *VirtualAccountTransactionUpdate) AddAdjustedDollars(v int) *VirtualAccountTransactionUpdate {
	_u.mutation.AddAdjustedDollars(v)
	return _u
}

// SetAdjustedCents sets the "adjusted_cents" field.
func (_u *VirtualAccountTransactionUpdate) SetAdjustedCents(v int) *VirtualAccountTransactionUpdate {
	_u.mutation.ResetAdjustedCents()
	_u.mutation.SetAdjustedCents(v)
	return _u
}

// SetNillableAdjustedCents sets the "adjusted_cents" field if the given value is not nil.
func (_u *VirtualAccountTransactionUpdate) SetNillableAdjustedCents(v *int) *VirtualAccountTransactionUpdate {
	if v != nil {
		_u.SetAdjustedCents(*v)
	}
	return _u
}

// AddAdjustedCents adds value to the "adjusted_cents" field.
func (_u *VirtualAccountTransactionUpdate) AddAdjustedCents(v int) *VirtualAccountTransactionUpdate {
	_u.mutation.AddAdjustedCents(v)
	return _u
}

// SetVirtualAccountID sets the "virtual_account_id" field.
func (_u *VirtualAccountTransactionUpdate) SetVirtualAccountID(v uuid.UUID) *VirtualAccountTransactionUpdate {
	_u.mutation.SetVirtualAccountID(v)
	return _u
}

// SetNillableVirtualAccountID sets the "virtual_account_id" field if the given value is not nil.
func (_u *VirtualAccountTransactionUpdate) SetNillableVirtualAccountID(v *uuid.UUID) *VirtualAccountTransactionUpdate {
	if v != nil {
		_u.SetVirtualAccountID(*v)
	}
	return _u
}

// SetVirtualAccount sets the "virtual_account" edge to the VirtualAccount entity.
func (_u *VirtualAccountTransactionUpdate) SetVirtualAccount(v *VirtualAccount) *VirtualAccountTransactionUpdate {
	return _u.SetVirtualAccountID(v.ID)
}

// Mutation returns the VirtualAccountTransactionMutation object of the builder.
func (_u *VirtualAccountTransactionUpdate) Mutation() *VirtualAccountTransactionMutation {
	return _u.mutation
}

// ClearVirtualAccount clears the "virtual_account" edge to the VirtualAccount entity.
func (_u *VirtualAccountTransactionUpdate) ClearVirtualAccount() *VirtualAccountTransactionUpdate {
	_u.mutation.ClearVirtualAccount()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *VirtualAccountTransactionUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *VirtualAccountTransactionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *VirtualAccountTransactionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *VirtualAccountTransactionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *VirtualAccountTransactionUpdate) check() error {
	if _u.mutation.VirtualAccountCleared() && len(_u.mutation.VirtualAccountIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "VirtualAccountTransaction.virtual_account"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *VirtualAccountTransactionUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *VirtualAccountTransactionUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *VirtualAccountTransactionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(virtualaccounttransaction.Table, virtualaccounttransaction.Columns, sqlgraph.NewFieldSpec(virtualaccounttransaction.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.AdjustedDollars(); ok {
		_spec.SetField(virtualaccounttransaction.FieldAdjustedDollars, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAdjustedDollars(); ok {
		_spec.AddField(virtualaccounttransaction.FieldAdjustedDollars, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AdjustedCents(); ok {
		_spec.SetField(virtualaccounttransaction.FieldAdjustedCents, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAdjustedCents(); ok {
		_spec.AddField(virtualaccounttransaction.FieldAdjustedCents, field.TypeInt, value)
	}
	if _u.mutation.VirtualAccountCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   virtualaccounttransaction.VirtualAccountTable,
			Columns: []string{virtualaccounttransaction.VirtualAccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(virtualaccount.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.VirtualAccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   virtualaccounttransaction.VirtualAccountTable,
			Columns: []string{virtualaccounttransaction.VirtualAccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(virtualaccount.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{virtualaccounttransaction.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// VirtualAccountTransactionUpdateOne is the builder for updating a single VirtualAccountTransaction entity.
type VirtualAccountTransactionUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *VirtualAccountTransactionMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetAdjustedDollars sets the "adjusted_dollars" field.
func (_u *VirtualAccountTransactionUpdateOne) SetAdjustedDollars(v int) *VirtualAccountTransactionUpdateOne {
	_u.mutation.ResetAdjustedDollars()
	_u.mutation.SetAdjustedDollars(v)
	return _u
}

// SetNillableAdjustedDollars sets the "adjusted_dollars" field if the given value is not nil.
func (_u *VirtualAccountTransactionUpdateOne) SetNillableAdjustedDollars(v *int) *VirtualAccountTransactionUpdateOne {
	if v != nil {
		_u.SetAdjustedDollars(*v)
	}
	return _u
}

// AddAdjustedDollars adds value to the "adjusted_dollars" field.
func (_u *VirtualAccountTransactionUpdateOne) AddAdjustedDollars(v int) *VirtualAccountTransactionUpdateOne {
	_u.mutation.AddAdjustedDollars(v)
	return _u
}

// SetAdjustedCents sets the "adjusted_cents" field.
func (_u *VirtualAccountTransactionUpdateOne) SetAdjustedCents(v int) *VirtualAccountTransactionUpdateOne {
	_u.mutation.ResetAdjustedCents()
	_u.mutation.SetAdjustedCents(v)
	return _u
}

// SetNillableAdjustedCents sets the "adjusted_cents" field if the given value is not nil.
func (_u *VirtualAccountTransactionUpdateOne) SetNillableAdjustedCents(v *int) *VirtualAccountTransactionUpdateOne {
	if v != nil {
		_u.SetAdjustedCents(*v)
	}
	return _u
}

// AddAdjustedCents adds value to the "adjusted_cents" field.
func (_u *VirtualAccountTransactionUpdateOne) AddAdjustedCents(v int) *VirtualAccountTransactionUpdateOne {
	_u.mutation.AddAdjustedCents(v)
	return _u
}

// SetVirtualAccountID sets the "virtual_account_id" field.
func (_u *VirtualAccountTransactionUpdateOne) SetVirtualAccountID(v uuid.UUID) *VirtualAccountTransactionUpdateOne {
	_u.mutation.SetVirtualAccountID(v)
	return _u
}

// SetNillableVirtualAccountID sets the "virtual_account_id" field if the given value is not nil.
func (_u *VirtualAccountTransactionUpdateOne) SetNillableVirtualAccountID(v *uuid.UUID) *VirtualAccountTransactionUpdateOne {
	if v != nil {
		_u.SetVirtualAccountID(*v)
	}
	return _u
}

// SetVirtualAccount sets the "virtual_account" edge to the VirtualAccount entity.
func (_u *VirtualAccountTransactionUpdateOne) SetVirtualAccount(v *VirtualAccount) *VirtualAccountTransactionUpdateOne {
	return _u.SetVirtualAccountID(v.ID)
}

// Mutation returns the VirtualAccountTransactionMutation object of the builder.
func (_u *VirtualAccountTransactionUpdateOne) Mutation() *VirtualAccountTransactionMutation {
	return _u.mutation
}

// ClearVirtualAccount clears the "virtual_account" edge to the VirtualAccount entity.
func (_u *VirtualAccountTransactionUpdateOne) ClearVirtualAccount() *VirtualAccountTransactionUpdateOne {
	_u.mutation.ClearVirtualAccount()
	return _u
}

// Where appends a list predicates to the VirtualAccountTransactionUpdate builder.
func (_u *VirtualAccountTransactionUpdateOne) Where(ps ...predicate.VirtualAccountTransaction) *VirtualAccountTransactionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *VirtualAccountTransactionUpdateOne) Select(field string, fields ...string) *VirtualAccountTransactionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated VirtualAccountTransaction entity.
func (_u *VirtualAccountTransactionUpdateOne) Save(ctx context.Context) (*VirtualAccountTransaction, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *VirtualAccountTransactionUpdateOne) SaveX(ctx context.Context) *VirtualAccountTransaction {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *VirtualAccountTransactionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *VirtualAccountTransactionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *VirtualAccountTransactionUpdateOne) check() error {
	if _u.mutation.VirtualAccountCleared() && len(_u.mutation.VirtualAccountIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "VirtualAccountTransaction.virtual_account"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *VirtualAccountTransactionUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *VirtualAccountTransactionUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *VirtualAccountTransactionUpdateOne) sqlSave(ctx context.Context) (_node *VirtualAccountTransaction, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(virtualaccounttransaction.Table, virtualaccounttransaction.Columns, sqlgraph.NewFieldSpec(virtualaccounttransaction.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "VirtualAccountTransaction.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, virtualaccounttransaction.FieldID)
		for _, f := range fields {
			if !virtualaccounttransaction.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != virtualaccounttransaction.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.AdjustedDollars(); ok {
		_spec.SetField(virtualaccounttransaction.FieldAdjustedDollars, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAdjustedDollars(); ok {
		_spec.AddField(virtualaccounttransaction.FieldAdjustedDollars, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AdjustedCents(); ok {
		_spec.SetField(virtualaccounttransaction.FieldAdjustedCents, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAdjustedCents(); ok {
		_spec.AddField(virtualaccounttransaction.FieldAdjustedCents, field.TypeInt, value)
	}
	if _u.mutation.VirtualAccountCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   virtualaccounttransaction.VirtualAccountTable,
			Columns: []string{virtualaccounttransaction.VirtualAccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(virtualaccount.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.VirtualAccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   virtualaccounttransaction.VirtualAccountTable,
			Columns: []string{virtualaccounttransaction.VirtualAccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(virtualaccount.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &VirtualAccountTransaction{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{virtualaccounttransaction.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
