// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"regulation/internal/ent/predicate"
	"regulation/internal/ent/virtualaccount"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// VirtualAccountDelete is the builder for deleting a VirtualAccount entity.
type VirtualAccountDelete struct {
	config
	hooks    []Hook
	mutation *VirtualAccountMutation
}

// Where appends a list predicates to the VirtualAccountDelete builder.
func (_d *VirtualAccountDelete) Where(ps ...predicate.VirtualAccount) *VirtualAccountDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *VirtualAccountDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *VirtualAccountDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *VirtualAccountDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(virtualaccount.Table, sqlgraph.NewFieldSpec(virtualaccount.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// VirtualAccountDeleteOne is the builder for deleting a single VirtualAccount entity.
type VirtualAccountDeleteOne struct {
	_d *VirtualAccountDelete
}

// Where appends a list predicates to the VirtualAccountDelete builder.
func (_d *VirtualAccountDeleteOne) Where(ps ...predicate.VirtualAccount) *VirtualAccountDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *VirtualAccountDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{virtualaccount.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *VirtualAccountDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
